/* AUTO-GENERATED by `npm run stitch:sync` from source/5880d8d9915f4a66b008c59381278cd0.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import TeamPage from '@/views/team';

export const metadata: Metadata = { title: "WrapFit — Cổng Hợp Tác Đối Tác & Quản Lý Team" };

export default TeamPage;
