/* AUTO-GENERATED by `npm run stitch:sync` from source/689a394a749743c18b0620e14392455d.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import CheckoutStep1Page from '@/views/checkout/step-1';

export const metadata: Metadata = { title: "WrapFit — Bước 1: Chọn Gói Cước & Tài Nguyên" };

export default CheckoutStep1Page;
