/* AUTO-GENERATED by `npm run stitch:sync` from source/99b7a9adc53a4f7db69c3d8b98fc9b2e.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import AdminRevenuePage from '@/views/admin/revenue';

export const metadata: Metadata = { title: "WrapFit Admin — Doanh Thu MRR & Quyết Toán Thuế VAT" };

export default AdminRevenuePage;
