/* AUTO-GENERATED by `npm run stitch:sync` from source/ba6c0fce8eb847a8a45264725b4b998c.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import NotificationsPage from '@/views/notifications';

export const metadata: Metadata = { title: "WrapFit — Trung Tâm Thông Báo Tương Tác Phân Loại" };

export default NotificationsPage;
