/* AUTO-GENERATED by `npm run stitch:sync` from source/1c24590034664885b91471cffe4c0d75.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import IntroBlueprintPage from '@/views/intro/blueprint';

export const metadata: Metadata = { title: "WrapFit — Trải Nghiệm 3D Intro Bàn Làm Việc CAD" };

export default IntroBlueprintPage;
