/* AUTO-GENERATED by `npm run stitch:sync` from source/569eb21b763443c6935e7de719542dbf.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import AdminStudioMonitoringPage from '@/views/admin/studio-monitoring';

export const metadata: Metadata = { title: "WrapFit Admin — WrapFit 3D Studio" };

export default AdminStudioMonitoringPage;
