/* AUTO-GENERATED by `npm run stitch:sync` from source/2bdc15fac5b0482ca1d7169df1357979.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import DashboardSettingsPage from '@/views/dashboard/settings';

export const metadata: Metadata = { title: "WrapFit — Dashboard Cài Đặt & Tài Khoản Chuyên Biệt" };

export default DashboardSettingsPage;
