/* AUTO-GENERATED by `npm run stitch:sync` from source/e200b7af01a1449a85d689d5b7fbc071.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import DashboardPage from '@/views/dashboard';

export const metadata: Metadata = { title: "WrapFit Platform — Dashboard Quản Lý Toàn Diện" };

export default DashboardPage;
