/* AUTO-GENERATED by `npm run stitch:sync` from source/2f24a2213dd74cd788a227223a8190c9.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
export { default } from '@/views/not-found';
