/* AUTO-GENERATED by `npm run stitch:sync` from source/93b051a5dca94de5bd0ed7ed759b4f7a.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { StitchRuntime } from '@/features/stitch/runtime/StitchRuntime';

export default function IntroMinimalPage() {
  return (
    <div data-stitch="intro-minimal" className="h-screen w-screen overflow-hidden bg-[#FAF8F5] text-[#1e1b19] antialiased relative">
{" "}
{/* BEGIN: ThreeJsSceneContainer */}
{" "}
{/* 3D Interactive Workbench scene filling 100vw and 100vh with centered camera, smooth continuous folds, and precision mat */}
{" "}
<div className="absolute inset-0 w-full h-full bg-[#FAF8F5] z-0 cursor-grab active:cursor-grabbing overflow-hidden" id="webgl-canvas-container">{" "}<canvas className="w-full h-full block" id="three-canvas" width="1600" height="160" style={{ "width": "1280px", "height": "128px" }} />{" "}</div>
{" "}
{/* END: ThreeJsSceneContainer */}
{" "}
{/* BEGIN: FloatingCenterCTA */}
{" "}
{/* Floating frosted-glass center button seamlessly blending into the background */}
{" "}
<main className="absolute inset-0 z-10 flex flex-col items-center justify-end pb-28 sm:pb-32 pointer-events-none" data-purpose="primary-conversion">{" "}<div className="pointer-events-auto text-center flex flex-col items-center group">{" "}{/* Spatial Start Button */}{" "}<a className="glass-panel relative flex items-center gap-3.5 px-6 py-3 rounded-full hover:scale-105 active:scale-95 transition-all duration-300 group-hover:border-neutral-300 group-hover:shadow-xl" data-purpose="experience-launch-trigger" href="#launch-studio" id="btn-launch-studio">{" "}<span className="flex h-2.5 w-2.5 relative">{" "}<span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-500 opacity-75" />{" "}<span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-emerald-600" />{" "}</span>{" "}<span className="text-sm font-medium tracking-tight text-neutral-900 group-hover:text-black">{" Bắt đầu trải nghiệm → "}</span>{" "}<span className="text-[11px] font-mono-tech text-neutral-600 bg-neutral-200/60 group-hover:bg-neutral-900 group-hover:text-white px-2.5 py-0.5 rounded-full transition-colors">{" 3D Studio "}</span>{" "}</a>{" "}{/* Subtitle description */}{" "}<p className="mt-2.5 text-xs text-neutral-500 font-mono-tech tracking-wide transition-opacity duration-300">{" Khảo sát mô hình dieline CAD, dụng cụ gia công và vật mẫu chuẩn xác "}</p>{" "}</div>{" "}</main>
{" "}
{/* END: FloatingCenterCTA */}
{" "}
{/* BEGIN: BottomStageSwitcherDock */}
{" "}
{/* 3-stage interactive packaging step selector dock */}
{" "}
<footer className="absolute bottom-6 inset-x-0 z-20 flex justify-center px-4 pointer-events-none" data-purpose="controller-dock">{" "}<div className="pointer-events-auto flex items-center p-1.5 rounded-full glass-panel border border-white/80 shadow-2xl space-x-1 sm:space-x-2">{" "}{/* Stage 1 Button */}{" "}<button className="stage-button active flex items-center gap-2 px-4 py-2 rounded-full text-xs font-mono-tech transition-all duration-200 bg-[#121517] text-white shadow-sm" data-stage="1" data-view="kit" id="stage-tab-1" type="button">{" "}<span className="w-1.5 h-1.5 rounded-full bg-white opacity-90" />{" "}<span>{"[Kit] Phôi CAD & Khung Dao"}</span>{" "}</button>{" "}{/* Stage 2 Button */}{" "}<button className="stage-button flex items-center gap-2 px-4 py-2 rounded-full text-xs font-mono-tech transition-all duration-200 text-neutral-700 hover:text-black hover:bg-black/5" data-stage="2" data-view="fold" id="stage-tab-2" type="button">{" "}<span className="w-1.5 h-1.5 rounded-full bg-neutral-400" />{" "}<span>[Drive] Nếp Gấp Mô Phỏng</span>{" "}</button>{" "}{/* Stage 3 Button */}{" "}<button className="stage-button flex items-center gap-2 px-4 py-2 rounded-full text-xs font-mono-tech transition-all duration-200 text-neutral-700 hover:text-black hover:bg-black/5" data-stage="3" data-view="studio" id="stage-tab-3" type="button">{" "}<span className="w-1.5 h-1.5 rounded-full bg-neutral-400" />{" "}<span>[Studio] Đóng Gói Thành Phẩm</span>{" "}</button>{" "}</div>{" "}</footer>
{" "}
{/* END: BottomStageSwitcherDock */}
{" "}
{/* BEGIN: ThreeJsWorkbenchImplementation */}
{" "}

{" "}
{/* END: ThreeJsWorkbenchImplementation */}
{" "}
{/* BEGIN: InteractiveHandlersScript */}
{" "}
{/* JavaScript glue bridging Stage buttons to smooth folding progression */}
{" "}

{" "}
{/* END: InteractiveHandlersScript */}
{" "}
      <StitchRuntime screen="intro-minimal" />
    </div>
  );
}
