import { FilePurpose, SubscriptionTier } from '@prisma/client';

const MB = 1024 * 1024;

const IMAGE_TYPES = { 'image/png': 'png', 'image/jpeg': 'jpg', 'image/webp': 'webp' };

/** Kinds of files users may upload (QR codes and print exports are generated by the backend). */
export type UploadPurpose = Exclude<FilePurpose, 'QR_CODE' | 'EXPORT'>;
export const UPLOAD_PURPOSES: UploadPurpose[] = ['LOGO', 'IMAGE', 'THUMBNAIL', 'AVATAR'];

/** Allowed formats (MIME -> file extension) and maximum size for each kind of upload. */
export const UPLOAD_RULES: Record<UploadPurpose, { types: Record<string, string>; maxBytes: number }> = {
  // Logos may be vectors (SVG, PDF) so the print export stays sharp (docs 07: up to 15 MB).
  LOGO: { types: { ...IMAGE_TYPES, 'image/svg+xml': 'svg', 'application/pdf': 'pdf' }, maxBytes: 15 * MB },
  IMAGE: { types: IMAGE_TYPES, maxBytes: 15 * MB },
  THUMBNAIL: { types: IMAGE_TYPES, maxBytes: 2 * MB },
  AVATAR: { types: IMAGE_TYPES, maxBytes: 2 * MB },
};

/**
 * Formats a browser would open as a page that can run scripts (SVG) or a viewer (PDF). They are stored with
 * `Content-Disposition: attachment`: opening their public URL downloads the file instead of running it on our CDN
 * domain, while `<img>` and the export worker still read them.
 */
export const DOWNLOAD_ONLY_TYPES: ReadonlySet<string> = new Set(['image/svg+xml', 'application/pdf']);

/** Total storage per user, by subscription tier. */
export const STORAGE_QUOTA_BYTES: Record<SubscriptionTier, number> = {
  FREE: 100 * MB,
  STARTER: 1024 * MB,
  PRO_BUSINESS: 10 * 1024 * MB,
};

/** Lifetime of a pre-signed upload URL. */
export const UPLOAD_URL_TTL_SECONDS = 300;

/**
 * An upload not confirmed yet still counts against the quota for this long: long enough for StorageMaintenanceTask
 * (every 10 minutes, on uploads older than CONFIRM_UPLOADS_AFTER_MS) to confirm it or drop it.
 */
export const PENDING_UPLOAD_RESERVE_MS = 60 * 60 * 1000;

/** Unconfirmed uploads are checked once their URL has expired (5 min) plus a margin for a slow upload. */
export const CONFIRM_UPLOADS_AFTER_MS = 15 * 60 * 1000;
