/* AUTO-GENERATED by `npm run stitch:sync` from source/ee872d035ca94c58862ba67ebf210aff.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import AdminMediaPage from '@/views/admin/media';

export const metadata: Metadata = { title: "WrapFit Admin — Quản Trị Đa Phương Tiện Thống Nhất & Tinh Chuẩn" };

export default AdminMediaPage;
