/* AUTO-GENERATED by `npm run stitch:sync` from source/35d57ad577324aa4b5123df2aa449482.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import AdminSecurityPage from '@/views/admin/security';

export const metadata: Metadata = { title: "WrapFit Admin — Bảo Mật Zero-Trust & RBAC" };

export default AdminSecurityPage;
