/* AUTO-GENERATED by `npm run stitch:sync` from source/81b3b87bc0194e90a9fe6252ae67d02e.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import AdminPrintShopsPage from '@/views/admin/print-shops';

export const metadata: Metadata = { title: "WrapFit Admin — Quản Lý Xưởng In" };

export default AdminPrintShopsPage;
