/* AUTO-GENERATED by `npm run stitch:sync` from source/0460ce4b82164674ac5f8930e9d737bd.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import DashboardBrandKitPage from '@/views/dashboard/brand-kit';

export const metadata: Metadata = { title: "WrapFit — Brand Kit & Vật Liệu Ký Gửi" };

export default DashboardBrandKitPage;
