/* AUTO-GENERATED by `npm run stitch:sync` from source/49731e481c8c41258c83713c4069d851.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import AdminPage from '@/views/admin';

export const metadata: Metadata = { title: "WrapFit Admin — Command Center Lướt Chart Tương Tác Kéo Thả" };

export default AdminPage;
