/* AUTO-GENERATED by `npm run stitch:sync` from source/93b051a5dca94de5bd0ed7ed759b4f7a.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import IntroMinimalPage from '@/views/intro/minimal';

export const metadata: Metadata = { title: "WrapFit — Trải Nghiệm 3D Intro Bàn Làm Việc" };

export default IntroMinimalPage;
