/* AUTO-GENERATED by `npm run stitch:sync` from source/8562c9c91936427aac61b7a163bf4d8e.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import AdminAccountsPage from '@/views/admin/accounts';

export const metadata: Metadata = { title: "WrapFit Admin — Danh Sách & Phân Hạng Tài Khoản" };

export default AdminAccountsPage;
