/* AUTO-GENERATED by `npm run stitch:sync` from source/0637e61ecb1d4c458105b0f92c79b505.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import AuthLoginPage from '@/views/auth/login';

export const metadata: Metadata = { title: "WrapFit — Xác Thực & Tài Khoản" };

export default AuthLoginPage;
