/* AUTO-GENERATED by `npm run stitch:sync` from source/64ae8cc2065f4cada9892a1fcd1a0dc1.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import EditorExportPage from '@/views/editor/export';

export const metadata: Metadata = { title: "WrapFit — Xuất File & Chia Sẻ" };

export default EditorExportPage;
