/* AUTO-GENERATED by `npm run stitch:sync` from source/5d6cc8b46f2640d49209c8b3973f093c.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import DashboardMaterialsPage from '@/views/dashboard/materials';

export const metadata: Metadata = { title: "WrapFit — Thư Viện Vật Liệu & Bảng Điều Khiển Tinh Gọn" };

export default DashboardMaterialsPage;
