/* AUTO-GENERATED by `npm run stitch:sync` from source/e5d224bd9f99441886fd6dd6673727f5.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import AdminDielineVaultPage from '@/views/admin/dieline-vault';

export const metadata: Metadata = { title: "WrapFit Admin — Dieline Vault & Kiểm Duyệt CAD" };

export default AdminDielineVaultPage;
