/* AUTO-GENERATED by `npm run stitch:sync` from source/bc597412e48e4660b2cdbcb2cac292a1.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import CheckoutStep3Page from '@/views/checkout/step-3';

export const metadata: Metadata = { title: "WrapFit — Bước 4: Xác Nhận & Cấp Phép Studio" };

export default CheckoutStep3Page;
