/* AUTO-GENERATED by `npm run stitch:sync` from source/c07e6191b5894077a0e34fc5088a141e.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import PricingPage from '@/views/pricing';

export const metadata: Metadata = { title: "WrapFit — Bảng Giá & Nâng Cấp" };

export default PricingPage;
