/* AUTO-GENERATED by `npm run stitch:sync` from source/76f2b2975700422e959e32b50f888aa3.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import AdminVaultQuotasPage from '@/views/admin/vault-quotas';

export const metadata: Metadata = { title: "WrapFit Admin — Cấp Quyền & Hạn Mức CAD Vault" };

export default AdminVaultQuotasPage;
