/* AUTO-GENERATED by `npm run stitch:sync` from source/4381d704e493424fa6ac99d748c04765.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import SupportPage from '@/views/support';

export const metadata: Metadata = { title: "WrapFit — Trung Tâm Hỗ Trợ Ma Trận Tinh Chuẩn" };

export default SupportPage;
