/* AUTO-GENERATED by `npm run stitch:sync` from source/9453d3217514482d8c12036305d3c024.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import DashboardProjectsPage from '@/views/dashboard/projects';

export const metadata: Metadata = { title: "WrapFit — Không Gian Dự Án Tối Giản" };

export default DashboardProjectsPage;
