// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/8562c9c91936427aac61b7a163bf4d8e.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  let buttons;
  try {
    // Keyboard shortcut CMD+F focus handler
    window.addEventListener('keydown', e => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'f') {
        const searchInput = document.getElementById('userQuickSearch');
        if (searchInput) {
          e.preventDefault();
          searchInput.focus();
        }
      }
    });

    // Quick filter state toggling demo
    (buttons = document.querySelectorAll('.filter-btn'));
    buttons.forEach(btn => {
      btn.addEventListener('click', () => {
        buttons.forEach(b => {
          b.className = 'filter-btn px-3.5 py-1.5 rounded-full bg-surface-container-lowest text-on-surface-variant hover:text-on-surface hover:bg-surface-container transition-all font-label-ui text-label-ui whitespace-nowrap';
        });
        btn.className = 'filter-btn px-3.5 py-1.5 rounded-full bg-primary-container text-on-primary font-label-ui text-label-ui shadow-sm whitespace-nowrap';
      });
    });
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  try {
    window.openUserDetail = function (name, id, email, tier, node, quota, percent, auth) {
      document.getElementById('drawerName').innerText = name;
      document.getElementById('drawerAvatar').innerText = name.split(' ').map(w => w[0]).slice(0, 2).join('');
      document.getElementById('drawerId').innerText = id;
      document.getElementById('drawerEmail').innerText = email;
      document.getElementById('drawerTier').innerText = tier;
      document.getElementById('drawerNode').innerText = node;
      document.getElementById('drawerQuota').innerText = quota;
      document.getElementById('drawerAuth').innerText = auth;
      document.getElementById('drawerQuotaBar').style.width = percent;
      document.getElementById('accountDetailDrawer').classList.remove('hidden');
    };
    window.closeUserDetail = function () {
      document.getElementById('accountDetailDrawer').classList.add('hidden');
    };
  } catch (error) {
    console.error('[stitch] script 2 failed', error);
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        window.openUserDetail('Tan Giang Packaging JSC', 'OEM-8824', 'tan-giang@pkg.vn', 'Enterprise OEM', 'HEIDELBERG-XL106 (Cluster #04)', '842 GB / 1000 GB', '84%', 'FIDO2 Hardware Key (Bảo Mật)');
      },
      /* click */ "1": function (event) {
        window.openUserDetail('Nguyen Minh Long', 'SOLO-4109', 'long.nm@cadcraft.design', 'Solo Pro', 'Kongsberg X24 Autofold', '18 GB / 50 GB', '36%', '2FA Authenticator TOTP');
      },
      /* click */ "2": function (event) {
        window.openUserDetail('Kiri Atelier Brand Packaging', 'B2B-1904', 'operations@kiri.studio', 'B2B Studio', 'Zünd G3 M-2500 Creasing', '194 GB / 200 GB', '97%', 'FIDO2 Hardware Key (Bảo Mật)');
      },
      /* click */ "3": function (event) {
        window.openUserDetail('Dong Phat Kraft Print Co.', 'REQ-0091', 'contact@dongphatprint.vn', 'Chờ Duyệt (Pending KYC)', 'Chưa liên kết Node', '0 GB / 20 GB', '0%', 'Chưa Thiết Lập');
      },
      /* click */ "4": function (event) {
        window.closeUserDetail();
      },
      /* click */ "5": function (event) {
        window.closeUserDetail();
      },
      /* click */ "6": function (event) {
        window.closeUserDetail();
      },
    },
  };
});
