// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/ee872d035ca94c58862ba67ebf210aff.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  try {
    (function initWrapFitMultimedia() {
      const cards = document.querySelectorAll('.hub-card');
      const overlay = document.getElementById('inspector-overlay');
      const modal = document.getElementById('inspector-modal');
      const closeModalBtn = document.getElementById('close-modal-btn');
      const dismissBtn = document.getElementById('modal-dismiss-btn');
      const searchInput = document.getElementById('hub-search-input');
      const filterTabs = document.querySelectorAll('.filter-tab');
      const mTitle = document.getElementById('modal-title');
      const mMeta = document.getElementById('modal-meta');
      const mBadge = document.getElementById('modal-badge');
      const mIcon = document.getElementById('modal-icon');
      const mIconContainer = document.getElementById('modal-icon-container');
      const mKpi1 = document.getElementById('modal-kpi1');
      const mKpi2 = document.getElementById('modal-kpi2');
      const mKpi3 = document.getElementById('modal-kpi3');
      const mActionBtn = document.getElementById('modal-action-btn');
      cards.forEach(card => {
        card.addEventListener('click', () => {
          const title = card.getAttribute('data-title');
          const meta = card.getAttribute('data-meta');
          const badge = card.getAttribute('data-badge');
          const icon = card.getAttribute('data-icon');
          const kpi1 = card.getAttribute('data-kpi1');
          const kpi2 = card.getAttribute('data-kpi2');
          const kpi3 = card.getAttribute('data-kpi3');
          const btnText = card.getAttribute('data-btn');
          const grad = card.getAttribute('data-gradient');
          mTitle.textContent = title;
          mMeta.textContent = meta;
          mIcon.textContent = icon;
          mKpi1.textContent = kpi1;
          mKpi2.textContent = kpi2;
          mKpi3.textContent = kpi3;
          mActionBtn.textContent = btnText || 'Truy Cập Ngay →';
          if (badge) {
            mBadge.textContent = badge;
            mBadge.classList.remove('hidden');
          } else {
            mBadge.classList.add('hidden');
          }
          mIconContainer.className = `w-14 h-14 rounded-2xl flex items-center justify-center shadow-sm text-white bg-gradient-to-tr ${grad}`;
          overlay.classList.remove('hidden', 'pointer-events-none');
          requestAnimationFrame(() => {
            overlay.classList.remove('opacity-0');
            overlay.classList.add('opacity-100');
            modal.classList.remove('scale-95');
            modal.classList.add('scale-100');
          });
        });
      });
      const closeModal = () => {
        overlay.classList.remove('opacity-100');
        overlay.classList.add('opacity-0');
        modal.classList.remove('scale-100');
        modal.classList.add('scale-95');
        setTimeout(() => {
          overlay.classList.add('hidden', 'pointer-events-none');
        }, 200);
      };
      closeModalBtn.addEventListener('click', closeModal);
      dismissBtn.addEventListener('click', closeModal);
      overlay.addEventListener('click', e => {
        if (e.target === overlay) closeModal();
      });
      filterTabs.forEach(tab => {
        tab.addEventListener('click', () => {
          filterTabs.forEach(t => {
            t.classList.remove('bg-secondary', 'text-white', 'font-medium');
            t.classList.add('text-stone-600');
          });
          tab.classList.add('bg-secondary', 'text-white', 'font-medium');
          tab.classList.remove('text-stone-600');
          const cat = tab.getAttribute('data-category');
          cards.forEach(card => {
            if (cat === 'all' || card.getAttribute('data-category') === cat) {
              card.style.display = 'flex';
            } else {
              card.style.display = 'none';
            }
          });
        });
      });
      searchInput.addEventListener('input', e => {
        const query = e.target.value.toLowerCase().trim();
        cards.forEach(card => {
          const title = card.getAttribute('data-title').toLowerCase();
          const meta = card.getAttribute('data-meta').toLowerCase();
          if (title.includes(query) || meta.includes(query)) {
            card.style.display = 'flex';
          } else {
            card.style.display = 'none';
          }
        });
      });
    })();
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
    },
  };
});
