// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/81b3b87bc0194e90a9fe6252ae67d02e.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  try {
    (function () {
      const searchInput = document.getElementById('tenantSearchInput');
      const cards = document.querySelectorAll('#deckContainer > div');
      const prevBtn = document.getElementById('deckPrevBtn');
      const nextBtn = document.getElementById('deckNextBtn');
      if (searchInput) {
        searchInput.addEventListener('input', function (e) {
          const val = (e.target.value || '').toLowerCase().trim();
          cards.forEach(card => {
            const text = card.textContent.toLowerCase();
            if (!val || text.includes(val)) {
              card.style.display = 'flex';
            } else {
              card.style.display = 'none';
            }
          });
        });
      }
      let currentDeckIndex = 1;
      const totalDecks = 4;
      function updateSlide(direction) {
        currentDeckIndex += direction;
        if (currentDeckIndex > totalDecks) currentDeckIndex = 1;
        if (currentDeckIndex < 1) currentDeckIndex = totalDecks;
        const deckLabel = document.querySelector('.relative .font-cad-dimension');
        if (deckLabel) {
          deckLabel.textContent = currentDeckIndex + ' / ' + totalDecks + ' DECK';
        }

        // Brief smooth feedback animation
        const container = document.getElementById('deckContainer');
        if (container) {
          container.style.opacity = '0.6';
          container.style.transform = direction > 0 ? 'translateX(6px)' : 'translateX(-6px)';
          setTimeout(() => {
            container.style.opacity = '1';
            container.style.transform = 'translateX(0)';
          }, 180);
        }
      }
      if (prevBtn) prevBtn.addEventListener('click', () => updateSlide(-1));
      if (nextBtn) nextBtn.addEventListener('click', () => updateSlide(1));
    })();
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        openPartnerDrawer('Packy Studio Co.', 'VN-HCM-8820', 'Zünd G3 CNC', '640 GB / 2 TB (32%)', '±0.024mm', 'Hoạt động', 'SGN-04', 'v2.4 Live');
      },
      /* click */ "1": function (event) {
        openPartnerDrawer('Atelier Luxe Paris', 'FR-PAR-0914', 'Kongsberg C64 + Hot Foil', '4.8 TB / 5 TB (96%)', '±0.015mm', 'Cảnh báo hạn mức', 'CDG-01', 'v2.3 Restrict');
      },
      /* click */ "2": function (event) {
        openPartnerDrawer('GreenBox Vietnam', 'VN-DNG-4102', 'Kongsberg C64 Auto', '1.1 TB / 3 TB (36%)', '±0.030mm', 'Hoạt động', 'DAD-02', 'v2.4 Live');
      },
      /* click */ "3": function (event) {
        openPartnerDrawer('NovaPrint Hub', 'VN-BD-6003', 'Bobst Novacut 106', '890 GB / 2 TB (44%)', '±0.020mm', 'Hoạt động', 'SGN-02', 'v2.4 HSM');
      },
    },
  };
});
