// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/76f2b2975700422e959e32b50f888aa3.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  // Classic scripts publish top-level functions on window.
  window.toggleFeatureCard = toggleFeatureCard;
  window.updateVaultCapacity = updateVaultCapacity;

  function toggleFeatureCard(card) {
    const indicator = card.querySelector('.toggle-indicator');
    const isActive = indicator.classList.contains('bg-secondary');
    if (isActive) {
      indicator.classList.remove('bg-secondary');
      indicator.classList.add('bg-surface-dim');
      card.classList.add('opacity-60');
    } else {
      indicator.classList.add('bg-secondary');
      indicator.classList.remove('bg-surface-dim');
      card.classList.remove('opacity-60');
    }
  }
  let slider;
  let usedText;
  let maxText;
  let percentText;
  let progressRing;
  function updateVaultCapacity(newMax) {
    const currentUsed = 4.8;
    const maxVal = parseFloat(newMax);
    slider.value = maxVal.toFixed(1);
    maxText.textContent = maxVal.toFixed(1);
    const percent = Math.min(100, Math.round(currentUsed / maxVal * 100));
    percentText.textContent = percent + '%';
    const circumference = 251.2;
    const offset = circumference - percent / 100 * circumference;
    progressRing.style.strokeDashoffset = offset;
  }
  let add1TbBtn;
  let add5TbBtn;
  let resetBtn;
  let saveBtn;
  try {
    (slider = document.getElementById('vaultStorageSlider'));
    (usedText = document.getElementById('usedStorageText'));
    (maxText = document.getElementById('maxStorageText'));
    (percentText = document.getElementById('capacityPercentText'));
    (progressRing = document.getElementById('vaultProgressRing'));
    if (slider) {
      slider.addEventListener('input', e => {
        updateVaultCapacity(e.target.value);
      });
    }
    (add1TbBtn = document.getElementById('add1TbBtn'));
    if (add1TbBtn) {
      add1TbBtn.addEventListener('click', () => {
        let val = Math.min(10.0, parseFloat(slider.value) + 1.0);
        updateVaultCapacity(val);
      });
    }
    (add5TbBtn = document.getElementById('add5TbBtn'));
    if (add5TbBtn) {
      add5TbBtn.addEventListener('click', () => {
        let val = Math.min(10.0, parseFloat(slider.value) + 5.0);
        updateVaultCapacity(val);
      });
    }
    (resetBtn = document.getElementById('resetDefaultsBtn'));
    if (resetBtn) {
      resetBtn.addEventListener('click', () => {
        updateVaultCapacity(5.0);
        const cards = document.querySelectorAll('.feature-toggle-card');
        cards.forEach(card => {
          const ind = card.querySelector('.toggle-indicator');
          ind.classList.add('bg-secondary');
          ind.classList.remove('bg-surface-dim');
          card.classList.remove('opacity-60');
        });
        const cnc = document.getElementById('cncApiToggle');
        if (cnc) cnc.checked = true;
      });
    }
    (saveBtn = document.getElementById('saveQuotaBtn'));
    if (saveBtn) {
      saveBtn.addEventListener('click', () => {
        const originalText = saveBtn.innerHTML;
        saveBtn.innerHTML = '<span class="material-symbols-outlined text-lg animate-spin">sync</span><span>Đang Đồng Bộ...</span>';
        setTimeout(() => {
          saveBtn.innerHTML = '<span class="material-symbols-outlined text-lg">check</span><span>Đã Cập Nhật!</span>';
          setTimeout(() => {
            saveBtn.innerHTML = originalText;
          }, 1800);
        }, 700);
      });
    }
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        openFlyout('tenant');
      },
      /* click */ "1": function (event) {
        openFlyout('billing');
      },
      /* click */ "2": function (event) {
        openFlyout('vault');
      },
      /* click */ "3": function (event) {
        event.stopPropagation();
      },
      /* click */ "4": function (event) {
        event.stopPropagation();
      },
      /* click */ "5": function (event) {
        openFlyout('features');
      },
      /* click */ "6": function (event) {
        toggleFeatureCard(this);
      },
      /* click */ "7": function (event) {
        toggleFeatureCard(this);
      },
      /* click */ "8": function (event) {
        toggleFeatureCard(this);
      },
      /* click */ "9": function (event) {
        closeFlyout();
      },
      /* click */ "10": function (event) {
        event.stopPropagation();
      },
      /* click */ "11": function (event) {
        closeFlyout();
      },
      /* click */ "12": function (event) {
        closeFlyout();
      },
    },
  };
});
