// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/35d57ad577324aa4b5123df2aa449482.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  try {
    window.openPolicyDetail = function (title, desc, mechanism, compliance, id, status) {
      const m = document.getElementById('policyModal');
      if (!m) return;
      document.getElementById('modalPolicyTitle').innerText = title;
      document.getElementById('modalPolicyDesc').innerText = desc;
      document.getElementById('modalPolicyCompliance').innerText = compliance;
      document.getElementById('modalPolicyId').innerText = id;
      document.getElementById('modalPolicyStatus').innerText = status;
      m.showModal();
    };
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        window.openPolicyDetail('Single-Tenant Data Isolation', 'Mã hóa AES-256 GCM độc lập trên từng kho bản vẽ CAD. Khóa quản lý bởi AWS KMS riêng biệt theo từng đối tác doanh nghiệp.', 'Hardware HSM • AWS KMS Multi-Region', 'FIPS 140-3 Cấp độ 3, ISO 27001 Annex A.10', 'BKLIT-HSM-2024-0982-ST', 'Đang hoạt động / Khóa xoay tự động 90 ngày');
      },
      /* click */ "1": function (event) {
        event.stopPropagation();
        this.classList.toggle('bg-primary-container');
        this.classList.toggle('bg-surface-dim');
        this.querySelector('span').classList.toggle('translate-x-5');
      },
      /* click */ "2": function (event) {
        window.openPolicyDetail('Session Idle Timeout', 'Tự động hủy token JWT và khóa màn hình 3D CAD Canvas nếu không phát hiện thao tác chuột hoặc bàn phím.', 'Client Idle Monitor • WebSocket Keep-Alive Ping', 'ISO/IEC 27001 A.11.2.8, NIST SP 800-63B', 'BKLIT-IDLE-AUTH-15M', '15 phút không hoạt động');
      },
      /* click */ "3": function (event) {
        event.stopPropagation();
        this.classList.toggle('bg-primary-container');
        this.classList.toggle('bg-surface-dim');
        this.querySelector('span').classList.toggle('translate-x-5');
      },
      /* click */ "4": function (event) {
        window.openPolicyDetail('IP Whitelisting Xưởng In & CNC', 'Chỉ định tuyến file dieline trực tiếp xuống bàn dao cắt số thông qua dải IP tĩnh đã định danh TLS v1.3.', 'mTLS Mutual Auth • Static VPN Gateway', 'IEC 62443 Industrial Cybersecurity', 'BKLIT-NET-ZUND-9081', '4 Cụm xưởng ủy quyền TLS 1.3');
      },
      /* click */ "5": function (event) {
        event.stopPropagation();
        this.classList.toggle('bg-primary-container');
        this.classList.toggle('bg-surface-dim');
        this.querySelector('span').classList.toggle('translate-x-5');
      },
      /* click */ "6": function (event) {
        window.openPolicyDetail('FIDO2 Biometric Enforcement DXF', 'Yêu cầu xác nhận sinh trắc học phần cứng hoặc Passkey khi kỹ sư ấn lệnh xuất dieline định dạng vector sản xuất.', 'WebAuthn PRF • Enclave Hardware Bound', 'FIDO Alliance Level 3 Certified', 'BKLIT-BIO-DXF-6610', 'Bắt buộc khi Export Vector');
      },
      /* click */ "7": function (event) {
        event.stopPropagation();
        this.classList.toggle('bg-primary-container');
        this.classList.toggle('bg-surface-dim');
        this.querySelector('span').classList.toggle('translate-x-5');
      },
      /* click */ "8": function (event) {
        window.openPolicyDetail('Audit Trail & WORM Immutable Logging', 'Tự động ký số SHA-256 từng lần chỉnh sửa kích thước bao bì. Ghi nhật ký vào phân vùng bất biến Write-Once-Read-Many.', 'Append-Only S3 Object Lock • Ledger Chain', 'SEC Rule 17a-4, SOC 2 Type II', 'BKLIT-WORM-CHAIN-7734', 'Ghi phân vùng WORM vĩnh cửu');
      },
      /* click */ "9": function (event) {
        event.stopPropagation();
        this.classList.toggle('bg-primary-container');
        this.classList.toggle('bg-surface-dim');
        this.querySelector('span').classList.toggle('translate-x-5');
      },
      /* click */ "10": function (event) {
        if (confirm('CẢNH BÁO: Kích hoạt ngắt toàn bộ phiên kết nối Zero-Trust?')) alert('Đã cô lập hệ thống bảo mật.');
      },
      /* click */ "11": function (event) {
        document.getElementById('policyModal').close();
      },
      /* click */ "12": function (event) {
        document.getElementById('policyModal').close();
      },
    },
  };
});
