// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/569eb21b763443c6935e7de719542dbf.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  try {
    (function () {
      const sliderGloss = document.getElementById('sliderGloss');
      const glossValue = document.getElementById('glossValue');
      const sliderRough = document.getElementById('sliderRough');
      const roughValue = document.getElementById('roughValue');
      const sliderFold = document.getElementById('sliderFold');
      const foldValue = document.getElementById('foldValue');
      const boxTop = document.getElementById('boxTop');
      const boxContainer = document.getElementById('boxContainer');
      if (sliderGloss && glossValue) {
        sliderGloss.addEventListener('input', e => {
          glossValue.textContent = e.target.value + '%';
        });
      }
      if (sliderRough && roughValue) {
        sliderRough.addEventListener('input', e => {
          roughValue.textContent = (e.target.value / 100).toFixed(2);
        });
      }
      if (sliderFold && foldValue && boxTop) {
        sliderFold.addEventListener('input', e => {
          const val = parseInt(e.target.value, 10);
          foldValue.textContent = val + '°';
          const rot = -18 - val * 0.45;
          boxTop.style.transform = `rotate(${rot}deg) scaleY(${Math.max(0.2, 0.95 - val / 300)})`;
        });
      }
      const btnPbr = document.getElementById('btn-mode-pbr');
      const btnWire = document.getElementById('btn-mode-wire');
      const btnHdri = document.getElementById('btn-mode-hdri');
      const modes = [btnPbr, btnWire, btnHdri];
      modes.forEach(btn => {
        if (!btn) return;
        btn.addEventListener('click', () => {
          modes.forEach(b => {
            b.className = 'px-space-md py-1.5 rounded-xl font-label-ui text-label-ui text-outline hover:text-on-surface transition-all flex items-center gap-space-xs';
          });
          btn.className = 'px-space-md py-1.5 rounded-xl font-label-ui text-label-ui bg-surface-container-lowest text-on-surface shadow-xs transition-all flex items-center gap-space-xs';
          if (boxContainer) {
            boxContainer.style.transform = `scale(0.96) rotate(${Math.random() * 4 - 2}deg)`;
            setTimeout(() => {
              boxContainer.style.transform = 'scale(1) rotate(0deg)';
            }, 200);
          }
        });
      });
    })();
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        const el = document.getElementById('shader-inspector-drawer');
        el.classList.toggle('hidden');
        el.classList.toggle('flex');
      },
      /* click */ "1": function (event) {
        document.getElementById('mesh-top-face').setAttribute('class', 'fill-surface-container-high transition-colors');
        document.getElementById('mesh-left-face').setAttribute('class', 'fill-surface-container transition-colors');
        document.getElementById('mesh-right-face').setAttribute('class', 'fill-surface-variant transition-colors');
      },
      /* click */ "2": function (event) {
        document.getElementById('mesh-top-face').setAttribute('class', 'fill-tertiary-fixed-dim transition-colors');
        document.getElementById('mesh-left-face').setAttribute('class', 'fill-tertiary-container transition-colors');
        document.getElementById('mesh-right-face').setAttribute('class', 'fill-tertiary transition-colors');
      },
      /* click */ "3": function (event) {
        document.getElementById('mesh-top-face').setAttribute('class', 'fill-surface-bright transition-colors');
        document.getElementById('mesh-left-face').setAttribute('class', 'fill-surface-container-low transition-colors');
        document.getElementById('mesh-right-face').setAttribute('class', 'fill-surface-container-high transition-colors');
      },
      /* click */ "4": function (event) {
        document.getElementById('shader-inspector-drawer').classList.add('hidden');
        document.getElementById('shader-inspector-drawer').classList.remove('flex');
      },
    },
  };
});
