// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/e5d224bd9f99441886fd6dd6673727f5.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  // Classic scripts publish top-level functions on window.
  window.goToSlide = goToSlide;
  window.openInspector = openInspector;
  window.closeInspector = closeInspector;
  window.approveInModal = approveInModal;

  let currentSlide;
  let totalSlides;
  let slideTrack;
  let prevBtn;
  let nextBtn;
  let dotBtns;
  let currentSlideLabel;
  let deckViewport;
  let slideTitles;
  function goToSlide(index) {
    if (index < 0) index = 0;
    if (index >= totalSlides) index = totalSlides - 1;
    currentSlide = index;

    // Update Slider Track Transform
    slideTrack.style.transform = `translateX(-${currentSlide * (100 / totalSlides)}%)`;

    // Update Dots
    dotBtns.forEach((btn, idx) => {
      if (idx === currentSlide) {
        btn.className = 'dot-btn w-6 h-2 rounded-full bg-primary transition-all duration-300';
      } else {
        btn.className = 'dot-btn w-2 h-2 rounded-full bg-surface-variant hover:bg-on-surface-variant transition-all duration-300';
      }
    });

    // Update Label
    if (currentSlideLabel) {
      currentSlideLabel.textContent = slideTitles[currentSlide];
    }

    // Update button visibility states (subtle opacity)
    prevBtn.style.opacity = currentSlide === 0 ? '0.4' : '1';
    nextBtn.style.opacity = currentSlide === totalSlides - 1 ? '0.4' : '1';
  }

  // Button event listeners
  let isDragging;
  let startX;
  let currentTranslate;
  let slideShrinkSlider;
  let slideShrinkVal;
  let slideGsmSlider;
  let slideGsmVal;
  let slide1ApproveBtn;
  let slide1InspectBtn;
  let slide2MeshBtn;
  let safeModeToggle;
  try {
    (currentSlide = 0);
    (totalSlides = 3);
    (slideTrack = document.getElementById('slideTrack'));
    (prevBtn = document.getElementById('prevSlideBtn'));
    (nextBtn = document.getElementById('nextSlideBtn'));
    (dotBtns = document.querySelectorAll('.dot-btn'));
    (currentSlideLabel = document.getElementById('currentSlideLabel'));
    (deckViewport = document.getElementById('deckViewport'));
    (slideTitles = ['1 / 3 • Thư Viện Bản Vẽ CAD', '2 / 3 • Bù Caliper & Co Ngót', '3 / 3 • Phân Bổ CNC & Xưởng In']);
    // Button event listeners
    prevBtn.addEventListener('click', () => goToSlide(currentSlide - 1));
    nextBtn.addEventListener('click', () => goToSlide(currentSlide + 1));
    dotBtns.forEach(btn => {
      btn.addEventListener('click', () => {
        const slideIndex = parseInt(btn.getAttribute('data-slide'), 10);
        goToSlide(slideIndex);
      });
    });

    // Keyboard Arrow navigation
    // Keyboard Arrow navigation
    window.addEventListener('keydown', e => {
      if (e.key === 'ArrowLeft') {
        goToSlide(currentSlide - 1);
      } else if (e.key === 'ArrowRight') {
        goToSlide(currentSlide + 1);
      }
    });

    // Drag / Swipe Gestures on Viewport
    (isDragging = false);
    (startX = 0);
    (currentTranslate = 0);
    deckViewport.addEventListener('mousedown', e => {
      // Don't drag if clicking an interactive input or button
      if (['INPUT', 'BUTTON', 'A'].includes(e.target.tagName)) return;
      isDragging = true;
      startX = e.clientX;
    });
    window.addEventListener('mouseup', e => {
      if (!isDragging) return;
      isDragging = false;
      const diffX = e.clientX - startX;
      if (diffX < -50) {
        goToSlide(currentSlide + 1);
      } else if (diffX > 50) {
        goToSlide(currentSlide - 1);
      }
    });

    // Touch support for mobile / tablets
    // Touch support for mobile / tablets
    deckViewport.addEventListener('touchstart', e => {
      if (['INPUT', 'BUTTON', 'A'].includes(e.target.tagName)) return;
      startX = e.touches[0].clientX;
    }, {
      passive: true
    });
    deckViewport.addEventListener('touchend', e => {
      const diffX = e.changedTouches[0].clientX - startX;
      if (diffX < -40) {
        goToSlide(currentSlide + 1);
      } else if (diffX > 40) {
        goToSlide(currentSlide - 1);
      }
    }, {
      passive: true
    });

    // Slider 2: Shrinkage and GSM interactive values
    (slideShrinkSlider = document.getElementById('slideShrinkSlider'));
    (slideShrinkVal = document.getElementById('slideShrinkVal'));
    if (slideShrinkSlider && slideShrinkVal) {
      slideShrinkSlider.addEventListener('input', e => {
        slideShrinkVal.textContent = parseFloat(e.target.value).toFixed(2) + ' mm';
      });
    }
    (slideGsmSlider = document.getElementById('slideGsmSlider'));
    (slideGsmVal = document.getElementById('slideGsmVal'));
    if (slideGsmSlider && slideGsmVal) {
      slideGsmSlider.addEventListener('input', e => {
        slideGsmVal.textContent = e.target.value + ' gsm';
      });
    }

    // Slide 1 Quick Approve
    (slide1ApproveBtn = document.getElementById('slide1ApproveBtn'));
    if (slide1ApproveBtn) {
      slide1ApproveBtn.addEventListener('click', function (e) {
        e.stopPropagation();
        this.innerHTML = '<span class="material-symbols-outlined text-[15px]">done_all</span><span>Đã Phê Duyệt</span>';
        this.classList.remove('bg-primary-container');
        this.classList.add('bg-secondary', 'text-on-secondary');
      });
    }

    // Slide 1 Inspect Caliper
    (slide1InspectBtn = document.getElementById('slide1InspectBtn'));
    if (slide1InspectBtn) {
      slide1InspectBtn.addEventListener('click', function (e) {
        e.stopPropagation();
        goToSlide(1); // Jump to Caliper tool
      });
    }

    // Slide 2 Mesh 3D Test
    (slide2MeshBtn = document.getElementById('slide2MeshBtn'));
    if (slide2MeshBtn) {
      slide2MeshBtn.addEventListener('click', function (e) {
        e.stopPropagation();
        const orig = this.innerHTML;
        this.innerHTML = '<span class="material-symbols-outlined text-[17px] animate-pulse">hourglass_top</span><span>Đang Render Mesh...</span>';
        setTimeout(() => {
          this.innerHTML = '<span class="material-symbols-outlined text-[17px] text-secondary">check_circle</span><span>Mesh Hoàn Hảo (0 Lỗi)</span>';
          setTimeout(() => {
            this.innerHTML = orig;
          }, 1800);
        }, 600);
      });
    }

    // Safe mode toggle
    (safeModeToggle = document.getElementById('safeModeToggle'));
    if (safeModeToggle) {
      safeModeToggle.addEventListener('click', function () {
        const thumb = this.querySelector('div');
        if (thumb.classList.contains('translate-x-4')) {
          thumb.classList.remove('translate-x-4');
          this.classList.remove('bg-secondary');
          this.classList.add('bg-surface-variant');
        } else {
          thumb.classList.add('translate-x-4');
          this.classList.remove('bg-surface-variant');
          this.classList.add('bg-secondary');
        }
      });
    }

    // Initialize slide state
    // Initialize slide state
    goToSlide(0);
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  function openInspector(code, title, dim, material, downloads, status) {
    const modal = document.getElementById('cadInspectorModal');
    if (!modal) return;
    document.getElementById('modalCode').textContent = code;
    document.getElementById('modalTitle').textContent = title;
    document.getElementById('modalDim').textContent = dim;
    document.getElementById('modalMaterial').textContent = material;
    document.getElementById('modalDownloads').textContent = downloads;
    document.getElementById('modalStatus').textContent = status;
    const btn = document.getElementById('modalApproveActionBtn');
    if (status === 'Chờ Duyệt') {
      btn.classList.remove('bg-secondary');
      btn.classList.add('bg-primary');
      btn.innerHTML = '<span class="material-symbols-outlined text-[15px]">check</span><span>Thẩm Định & Phê Duyệt</span>';
    } else {
      btn.classList.remove('bg-primary');
      btn.classList.add('bg-secondary');
      btn.innerHTML = '<span class="material-symbols-outlined text-[15px]">done_all</span><span>Đã Chứng Nhận CNC</span>';
    }
    modal.classList.remove('hidden');
  }
  function closeInspector() {
    const modal = document.getElementById('cadInspectorModal');
    if (modal) modal.classList.add('hidden');
  }
  function approveInModal() {
    const btn = document.getElementById('modalApproveActionBtn');
    btn.classList.remove('bg-primary');
    btn.classList.add('bg-secondary');
    btn.innerHTML = '<span class="material-symbols-outlined text-[15px]">done_all</span><span>Đã Phê Duyệt Thành Công</span>';
    document.getElementById('modalStatus').textContent = 'SẴN SÀNG';
    document.getElementById('modalStatus').className = 'text-[11px] font-cad-spec-micro px-2 py-0.5 rounded-full bg-secondary-fixed text-on-secondary-fixed';
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        openInspector('FEFCO 0215', 'Hộp Cài Đáy Khóa', '210 × 140 × 65 mm', 'Carton Ivory 350gsm', '18.240', 'Sẵn Sàng');
      },
      /* click */ "1": function (event) {
        openInspector('ECMA-210', 'Hộp Nam Châm Nắp Gập', '185 × 120 × 45 mm', 'Bìa Cứng Greyboard 2.0mm', '12.450', 'Sẵn Sàng');
      },
      /* click */ "2": function (event) {
        openInspector('FEFCO 0427', 'Hộp Pizza Giác Cắt', '320 × 320 × 45 mm', 'Kraft mộc tự nhiên', '8.120', 'Sẵn Sàng');
      },
      /* click */ "3": function (event) {
        openInspector('FEFCO CUSTOM', 'Hộp Trượt Khay Rút Đáy', '160 × 90 × 35 mm', 'Carton sóng E 1.8mm', 'Chưa xuất', 'Chờ Duyệt');
      },
      /* click */ "4": function (event) {
        closeInspector();
      },
      /* click */ "5": function (event) {
        approveInModal();
      },
    },
  };
});
