// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/99b7a9adc53a4f7db69c3d8b98fc9b2e.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  try {
    (function initDeckSlider() {
      const track = document.getElementById('deckTrack');
      const prevBtn = document.getElementById('prevSlideBtn');
      const nextBtn = document.getElementById('nextSlideBtn');
      const dots = document.querySelectorAll('.dot-indicator');
      const totalSlides = 3;
      let currentIndex = 0;
      function updateUI(index) {
        currentIndex = Math.max(0, Math.min(index, totalSlides - 1));

        // Update arrow button disabled state
        prevBtn.disabled = currentIndex === 0;
        nextBtn.disabled = currentIndex === totalSlides - 1;

        // Update pagination dots (active dot is an elongated pill)
        dots.forEach((dot, idx) => {
          if (idx === currentIndex) {
            dot.classList.remove('w-2', 'bg-surface-variant');
            dot.classList.add('w-8', 'bg-primary');
          } else {
            dot.classList.remove('w-8', 'bg-primary');
            dot.classList.add('w-2', 'bg-surface-variant');
          }
        });
      }
      function scrollToSlide(index) {
        const slideWidth = track.clientWidth;
        track.scrollTo({
          left: index * slideWidth,
          behavior: 'smooth'
        });
        updateUI(index);
      }

      // Button listeners
      prevBtn.addEventListener('click', () => {
        if (currentIndex > 0) scrollToSlide(currentIndex - 1);
      });
      nextBtn.addEventListener('click', () => {
        if (currentIndex < totalSlides - 1) scrollToSlide(currentIndex + 1);
      });

      // Dot click listeners
      dots.forEach(dot => {
        dot.addEventListener('click', e => {
          const target = parseInt(e.currentTarget.getAttribute('data-target'), 10);
          scrollToSlide(target);
        });
      });

      // Synchronize index on scroll / drag swipe
      let scrollTimeout;
      track.addEventListener('scroll', () => {
        clearTimeout(scrollTimeout);
        scrollTimeout = setTimeout(() => {
          const slideWidth = track.clientWidth;
          if (slideWidth > 0) {
            const newIndex = Math.round(track.scrollLeft / slideWidth);
            if (newIndex !== currentIndex) {
              updateUI(newIndex);
            }
          }
        }, 60);
      });

      // Keyboard left / right arrow support
      track.addEventListener('keydown', e => {
        if (e.key === 'ArrowRight' && currentIndex < totalSlides - 1) {
          e.preventDefault();
          scrollToSlide(currentIndex + 1);
        } else if (e.key === 'ArrowLeft' && currentIndex > 0) {
          e.preventDefault();
          scrollToSlide(currentIndex - 1);
        }
      });

      // Initial state
      updateUI(0);
    })();
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
    },
  };
});
