// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/49731e481c8c41258c83713c4069d851.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  try {
    window.currentSectionIndex = 0;
    window.totalSections = 4;
    window.goToSection = function (idx) {
      if (idx < 0) idx = 0;
      if (idx >= window.totalSections) idx = window.totalSections - 1;
      window.currentSectionIndex = idx;
      var deck = document.getElementById('section-deck');
      if (deck) {
        deck.style.transition = 'transform 0.45s cubic-bezier(0.16, 1, 0.3, 1)';
        deck.style.transform = 'translateX(-' + idx * 25 + '%)';
      }
      // Update dots
      var dots = document.querySelectorAll('.deck-dot');
      dots.forEach(function (dot, i) {
        if (i === idx) {
          dot.className = 'deck-dot w-6 h-2.5 rounded-full bg-[#004ac6] transition-all';
        } else {
          dot.className = 'deck-dot w-2.5 h-2.5 rounded-full bg-[#e9e1dd] hover:bg-[#737686] transition-all';
        }
      });
    };
    window.stepSection = function (step) {
      window.goToSection(window.currentSectionIndex + step);
    };
    window.addEventListener('keydown', function (e) {
      if (e.key === 'ArrowRight') window.stepSection(1);
      if (e.key === 'ArrowLeft') window.stepSection(-1);
    });

    // Drag-to-slide / Swipe Mouse and Touch Tracking
    // Drag-to-slide / Swipe Mouse and Touch Tracking
    (function initSwipe() {
      var container = document.getElementById('swipe-container');
      var deck = document.getElementById('section-deck');
      if (!container || !deck) return;
      var startX = 0;
      var currentX = 0;
      var isDragging = false;
      var containerWidth = 0;
      function onStart(x) {
        isDragging = true;
        startX = x;
        currentX = x;
        containerWidth = container.offsetWidth || 1;
        deck.style.transition = 'none';
      }
      function onMove(x) {
        if (!isDragging) return;
        currentX = x;
        var diffX = currentX - startX;
        var baseTranslate = -(window.currentSectionIndex * 25);
        var offsetPercent = diffX / containerWidth * 25;

        // Add friction on edges
        if (window.currentSectionIndex === 0 && diffX > 0 || window.currentSectionIndex === window.totalSections - 1 && diffX < 0) {
          offsetPercent *= 0.3;
        }
        deck.style.transform = 'translateX(' + (baseTranslate + offsetPercent) + '%)';
      }
      function onEnd() {
        if (!isDragging) return;
        isDragging = false;
        var diffX = currentX - startX;
        var threshold = 50; // min px drag to trigger slide
        if (diffX < -threshold) {
          window.stepSection(1);
        } else if (diffX > threshold) {
          window.stepSection(-1);
        } else {
          window.goToSection(window.currentSectionIndex);
        }
      }

      // Mouse Events
      container.addEventListener('mousedown', function (e) {
        // Don't drag if clicking a button or link
        if (e.target.closest('button') || e.target.closest('a')) return;
        onStart(e.clientX);
      });
      window.addEventListener('mousemove', function (e) {
        onMove(e.clientX);
      });
      window.addEventListener('mouseup', function (e) {
        onEnd();
      });

      // Touch Events
      container.addEventListener('touchstart', function (e) {
        if (e.target.closest('button') || e.target.closest('a')) return;
        onStart(e.touches[0].clientX);
      }, {
        passive: true
      });
      container.addEventListener('touchmove', function (e) {
        onMove(e.touches[0].clientX);
      }, {
        passive: true
      });
      container.addEventListener('touchend', function () {
        onEnd();
      });
    })();
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        window.stepSection(-1);
      },
      /* click */ "1": function (event) {
        window.stepSection(1);
      },
      /* click */ "2": function (event) {
        window.goToSection(1);
      },
      /* click */ "3": function (event) {
        window.goToSection(0);
      },
      /* click */ "4": function (event) {
        window.goToSection(2);
      },
      /* click */ "5": function (event) {
        window.goToSection(1);
      },
      /* click */ "6": function (event) {
        window.goToSection(3);
      },
      /* click */ "7": function (event) {
        window.goToSection(2);
      },
      /* click */ "8": function (event) {
        window.goToSection(0);
      },
      /* click */ "9": function (event) {
        window.goToSection(1);
      },
      /* click */ "10": function (event) {
        window.goToSection(2);
      },
      /* click */ "11": function (event) {
        window.goToSection(3);
      },
    },
  };
});
