// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/0637e61ecb1d4c458105b0f92c79b505.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  // Classic scripts publish top-level functions on window.
  window.toggleAuthMode = toggleAuthMode;
  window.togglePassword = togglePassword;
  window.submitAuth = submitAuth;

  let isRegisterMode;
  function toggleAuthMode() {
    isRegisterMode = !isRegisterMode;
    const topLabel = document.getElementById('top-switch-label');
    const topBtn = document.getElementById('top-switch-btn');
    const authTitle = document.getElementById('auth-title');
    const authDesc = document.getElementById('auth-desc');
    const fieldFullname = document.getElementById('field-fullname');
    const forgotContainer = document.getElementById('forgot-password-container');
    const submitBtn = document.getElementById('submit-btn');
    if (isRegisterMode) {
      topLabel.textContent = 'Đã có tài khoản?';
      topBtn.textContent = 'Đăng nhập';
      authTitle.innerHTML = 'Tạo tài khoản <span class="text-brand font-extrabold">WrapFit</span>';
      authDesc.textContent = 'Khởi tạo tài khoản miễn phí để thiết kế khuôn bế & mô phỏng 3D ngay lập tức.';
      fieldFullname.classList.remove('hidden');
      forgotContainer.classList.add('hidden');
      submitBtn.innerHTML = '<span>Bắt đầu miễn phí</span>';
    } else {
      topLabel.textContent = 'Chưa có tài khoản?';
      topBtn.textContent = 'Đăng ký';
      authTitle.innerHTML = 'Đăng nhập vào <span class="text-brand font-extrabold">WrapFit</span>';
      authDesc.textContent = 'Chào mừng bạn trở lại, vui lòng nhập thông tin để truy cập không gian CAD & 3D Studio.';
      fieldFullname.classList.add('hidden');
      forgotContainer.classList.remove('hidden');
      submitBtn.innerHTML = '<span>Đăng nhập</span>';
    }
  }
  function togglePassword() {
    const pwdInput = document.getElementById('input-password');
    const eyeIcon = document.getElementById('eye-icon');
    if (pwdInput.type === 'password') {
      pwdInput.type = 'text';
      eyeIcon.textContent = 'visibility_off';
    } else {
      pwdInput.type = 'password';
      eyeIcon.textContent = 'visibility';
    }
  }
  function submitAuth() {
    const toast = document.getElementById('toast');
    const toastText = document.getElementById('toast-text');
    toastText.textContent = isRegisterMode ? 'Đăng ký thành công! Đang kích hoạt tài khoản studio...' : 'Đăng nhập thành công! Đang nạp không gian CAD...';
    toast.classList.remove('translate-y-20', 'opacity-0');
    toast.classList.add('translate-y-0', 'opacity-100');
    setTimeout(() => {
      toast.classList.add('translate-y-20', 'opacity-0');
      toast.classList.remove('translate-y-0', 'opacity-100');
    }, 2500);
  }
  try {
    (isRegisterMode = false);
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
      /* submit */ "0": function (event) {
        event.preventDefault();
        submitAuth();
      },
      /* click */ "1": function (event) {
        togglePassword();
      },
      /* click */ "2": function (event) {
        toggleAuthMode();
      },
    },
  };
});
