// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/689a394a749743c18b0620e14392455d.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  // Classic scripts publish top-level functions on window.
  window.updatePricing = updatePricing;
  window.selectPlan = selectPlan;
  window.adjustSeats = adjustSeats;
  window.switchBilling = switchBilling;
  window.proceedToPayment = proceedToPayment;
  window.renderPlanDetails = renderPlanDetails;

  let currentPlan;
  let isYearly;
  let seats;
  let cardBasic;
  let cardPro;
  let checkBasic;
  let checkPro;
  let priceBasicEl;
  let priceProEl;
  let seatCountEl;
  let displaySeatRateEl;
  let displayTotalPriceEl;
  let dockTotalPreviewEl;
  let cloudStorageValEl;
  let storageBarEl;
  let toggleMonthly;
  let toggleYearly;
  function updatePricing() {
    const basicRate = isYearly ? 8 : 10;
    const proRate = isYearly ? 16 : 20;
    priceBasicEl.textContent = `$${basicRate}`;
    priceProEl.textContent = `$${proRate}`;
    const currentSeatRate = currentPlan === 'pro' ? proRate : basicRate;
    if (displaySeatRateEl) displaySeatRateEl.textContent = `$${currentSeatRate} / ghế`;
    const total = seats * currentSeatRate;
    displayTotalPriceEl.textContent = `$${total}`;
    dockTotalPreviewEl.textContent = `$${total}/tháng`;

    // Storage calculation visual
    const storagePerSeat = currentPlan === 'pro' ? 100 : 20;
    const totalStorage = seats * storagePerSeat;
    cloudStorageValEl.textContent = `${totalStorage.toLocaleString()} GB Cloud`;
    const pct = Math.min(100, Math.max(15, seats / 70 * 100));
    if (storageBarEl) storageBarEl.style.width = `${pct}%`;
  }
  function selectPlan(plan) {
    currentPlan = plan;
    if (plan === 'pro') {
      cardPro.classList.add('ring-2', 'ring-primary-container', 'shadow-xl', 'shadow-primary/5', 'bg-white');
      cardPro.classList.remove('bg-white/70');
      checkPro.className = 'w-6 h-6 rounded-full bg-primary-container flex items-center justify-center text-white shadow-sm';
      checkPro.innerHTML = '<span class="material-symbols-outlined text-[16px]">check</span>';
      cardBasic.classList.remove('ring-2', 'ring-primary-container', 'shadow-xl', 'bg-white');
      cardBasic.classList.add('bg-white/70');
      checkBasic.className = 'w-6 h-6 rounded-full bg-surface-container flex items-center justify-center text-white';
      checkBasic.innerHTML = '';
    } else {
      cardBasic.classList.add('ring-2', 'ring-primary-container', 'shadow-xl', 'shadow-primary/5', 'bg-white');
      cardBasic.classList.remove('bg-white/70');
      checkBasic.className = 'w-6 h-6 rounded-full bg-primary-container flex items-center justify-center text-white shadow-sm';
      checkBasic.innerHTML = '<span class="material-symbols-outlined text-[16px]">check</span>';
      cardPro.classList.remove('ring-2', 'ring-primary-container', 'shadow-xl', 'shadow-primary/5', 'bg-white');
      cardPro.classList.add('bg-white/70');
      checkPro.className = 'w-6 h-6 rounded-full bg-surface-container flex items-center justify-center text-white';
      checkPro.innerHTML = '';
    }
    updatePricing();
  }
  function adjustSeats(delta) {
    const newSeats = seats + delta;
    if (newSeats >= 1 && newSeats <= 200) {
      seats = newSeats;
      if (seatCountEl) seatCountEl.textContent = seats;
      updatePricing();
    }
  }
  function switchBilling(yearly) {
    isYearly = yearly;
    if (yearly) {
      toggleYearly.className = 'px-5 py-2 rounded-full font-label-ui text-xs font-semibold bg-white text-primary shadow-sm transition-all duration-200 flex items-center gap-1.5';
      toggleMonthly.className = 'px-5 py-2 rounded-full font-label-ui text-xs font-semibold text-on-surface-variant hover:text-on-surface transition-all duration-200';
    } else {
      toggleMonthly.className = 'px-5 py-2 rounded-full font-label-ui text-xs font-semibold bg-white text-primary shadow-sm transition-all duration-200';
      toggleYearly.className = 'px-5 py-2 rounded-full font-label-ui text-xs font-semibold text-on-surface-variant hover:text-on-surface transition-all duration-200 flex items-center gap-1.5';
    }
    updatePricing();
  }
  function proceedToPayment() {
    const btn = document.getElementById('btn-submit');
    if (btn) {
      btn.innerHTML = '<span class="material-symbols-outlined animate-spin text-[18px]">progress_activity</span> Chuyển sang Bước 2...';
    }
    setTimeout(() => {
      window.location.href = '/checkout/step-2';
    }, 600);
  }

  // Init state
  try {
    (currentPlan = 'pro');
    (isYearly = false);
    (seats = 32);
    (cardBasic = document.getElementById('card-basic'));
    (cardPro = document.getElementById('card-pro'));
    (checkBasic = document.getElementById('check-basic'));
    (checkPro = document.getElementById('check-pro'));
    (priceBasicEl = document.getElementById('price-basic'));
    (priceProEl = document.getElementById('price-pro'));
    (seatCountEl = document.getElementById('seat-count'));
    (displaySeatRateEl = document.getElementById('display-seat-rate'));
    (displayTotalPriceEl = document.getElementById('display-total-price'));
    (dockTotalPreviewEl = document.getElementById('dock-total-preview'));
    (cloudStorageValEl = document.getElementById('cloud-storage-val'));
    (storageBarEl = document.getElementById('storage-bar'));
    (toggleMonthly = document.getElementById('toggle-monthly'));
    (toggleYearly = document.getElementById('toggle-yearly'));
    // Init state
    updatePricing();
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  let planData;
  function renderPlanDetails() {
    const data = planData[currentPlan];
    const price = isYearly ? data.yearlyPrice : data.monthlyPrice;
    const badgeEl = document.getElementById('detail-badge');
    const nameEl = document.getElementById('detail-plan-name');
    const iconEl = document.getElementById('detail-icon');
    const storageEl = document.getElementById('cloud-storage-val');
    const commercialEl = document.getElementById('detail-commercial');
    const perksListEl = document.getElementById('detail-perks-list');
    const priceEl = document.getElementById('display-total-price');
    const subEl = document.getElementById('display-total-sub');
    const billingNoteEl = document.getElementById('billing-note');
    const dockPreviewEl = document.getElementById('dock-total-preview');
    const mascotEl = document.getElementById('mascot-advice');
    if (badgeEl) badgeEl.innerHTML = data.badge;
    if (nameEl) nameEl.textContent = data.name;
    if (iconEl) iconEl.innerHTML = '<span class="material-symbols-outlined text-[20px]">' + data.icon + '</span>';
    if (storageEl) storageEl.textContent = data.storage;
    if (commercialEl) commercialEl.textContent = data.commercial;
    if (priceEl) priceEl.textContent = '$' + price;
    if (subEl) subEl.textContent = isYearly ? '/ tháng (trả hàng năm)' : '/ tháng';
    if (dockPreviewEl) dockPreviewEl.textContent = '$' + price + (isYearly ? '/tháng*' : '/tháng');
    if (billingNoteEl) {
      billingNoteEl.textContent = isYearly ? 'Tiết kiệm 20% thanh toán cả năm trả trước $' + price * 12 + '/năm' : 'Thanh toán linh hoạt từng tháng, hủy bất cứ lúc nào';
    }
    if (mascotEl) {
      mascotEl.innerHTML = data.mascot;
    }
    if (perksListEl) {
      perksListEl.innerHTML = data.perks.map(perk => `
          <div class="flex items-start gap-3 text-xs text-on-surface animate-fadeIn">
            <div class="w-5 h-5 rounded-full bg-secondary-container/80 flex items-center justify-center text-on-secondary-container shrink-0 mt-0.5">
              <span class="material-symbols-outlined text-[13px]">check</span>
            </div>
            <span>${perk}</span>
          </div>
        `).join('');
    }
  }

  // Override selectPlan & switchBilling to ensure immediate updates
  let origSelectPlan;
  let origSwitchBilling;
  try {
    (planData = {
      basic: {
        name: 'Basic Studio',
        badge: '<span class="material-symbols-outlined text-[15px]">verified</span> Gói Cá Nhân Khởi Đầu - Basic',
        icon: 'square_foot',
        monthlyPrice: 10,
        yearlyPrice: 8,
        storage: '20 GB Dieline Cloud',
        commercial: 'Cá nhân & Portfolio',
        mascot: '“Gói Basic Studio rất thích hợp để bắt đầu dựng mẫu nhanh các bao bì ECMA/FEFCO và xuất DXF 1:1 chuẩn xác!”',
        perks: ['120+ Mẫu khuôn hộp CAD tiêu chuẩn (FEFCO / ECMA phổ biến)', 'Xuất file vector CAD 2D tỉ lệ 1:1 định dạng DXF & PDF phân lớp', '20 GB Cloud Storage cá nhân lưu trữ bản vẽ và asset', 'Kiểm tra kích thước và chu vi cơ bản', 'Hỗ trợ kỹ thuật qua ticket tiêu chuẩn trong 24h']
      },
      pro: {
        name: 'Solo Pro Pass',
        badge: '<span class="material-symbols-outlined text-[15px]">verified</span> Gói Cá Nhân Cao Cấp - Pro Pass',
        icon: 'workspace_premium',
        monthlyPrice: 20,
        yearlyPrice: 16,
        storage: '100 GB Cloud Vault',
        commercial: 'Thương mại vĩnh viễn',
        mascot: '“Với Solo Pro Pass, hệ thống bù 0.25mm rãnh cấn tự động giúp loại bỏ hoàn toàn lỗi gãy sóng giấy carton sóng E/F khi lên khuôn dao bế!”',
        perks: ['Mở khóa 1.250+ Mẫu khuôn CAD & Dieline cao cấp toàn diện', 'Tự động bù co giãn nếp gấp và đo Caliper giấy chính xác', 'Mô phỏng 3D Origami gập mở thời gian thực & PBR Shaders ép kim 22K', 'Báo cáo thẩm định an toàn bao bì FitCheck™ Pass 100%', 'Xuất không giới hạn định dạng chế bản in CNC, Laser, DWG, DXF, PDF', '100 GB Cloud Vault bảo mật chuẩn mã hóa công nghiệp', 'Hỗ trợ kỹ thuật ưu tiên 24/7 trực tiếp cùng Kỹ sư CAD']
      }
    });
    (origSelectPlan = window.selectPlan);
    window.selectPlan = function (plan) {
      if (typeof origSelectPlan === 'function') {
        try {
          origSelectPlan(plan);
        } catch (e) {}
      }
      currentPlan = plan;
      const cardBasic = document.getElementById('card-basic');
      const cardPro = document.getElementById('card-pro');
      const checkBasic = document.getElementById('check-basic');
      const checkPro = document.getElementById('check-pro');
      if (plan === 'pro') {
        cardPro.className = 'relative cursor-pointer rounded-3xl p-6 bg-white subtle-shadow hover-lift flex flex-col justify-between transition-all duration-300 ring-2 ring-primary-container shadow-xl shadow-primary/5';
        checkPro.className = 'w-6 h-6 rounded-full bg-primary-container flex items-center justify-center text-white shadow-sm';
        checkPro.innerHTML = '<span class="material-symbols-outlined text-[16px]">check</span>';
        cardBasic.className = 'group relative cursor-pointer rounded-3xl p-6 bg-white/70 hover:bg-white subtle-shadow hover-lift flex flex-col justify-between transition-all duration-300';
        checkBasic.className = 'w-6 h-6 rounded-full bg-surface-container flex items-center justify-center text-white';
        checkBasic.innerHTML = '';
      } else {
        cardBasic.className = 'group relative cursor-pointer rounded-3xl p-6 bg-white subtle-shadow hover-lift flex flex-col justify-between transition-all duration-300 ring-2 ring-primary-container shadow-xl shadow-primary/5';
        checkBasic.className = 'w-6 h-6 rounded-full bg-primary-container flex items-center justify-center text-white shadow-sm';
        checkBasic.innerHTML = '<span class="material-symbols-outlined text-[16px]">check</span>';
        cardPro.className = 'relative cursor-pointer rounded-3xl p-6 bg-white/70 hover:bg-white subtle-shadow hover-lift flex flex-col justify-between transition-all duration-300';
        checkPro.className = 'w-6 h-6 rounded-full bg-surface-container flex items-center justify-center text-white';
        checkPro.innerHTML = '';
      }
      renderPlanDetails();
    };
    (origSwitchBilling = window.switchBilling);
    window.switchBilling = function (yearly) {
      if (typeof origSwitchBilling === 'function') {
        try {
          origSwitchBilling(yearly);
        } catch (e) {}
      }
      isYearly = yearly;
      renderPlanDetails();
    };

    // Initial render execution
    // Initial render execution
    renderPlanDetails();
  } catch (error) {
    console.error('[stitch] script 2 failed', error);
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        switchBilling(false);
      },
      /* click */ "1": function (event) {
        switchBilling(true);
      },
      /* click */ "2": function (event) {
        selectPlan('basic');
      },
      /* click */ "3": function (event) {
        selectPlan('pro');
      },
      /* click */ "4": function (event) {
        proceedToPayment();
      },
    },
  };
});
