// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/bc597412e48e4660b2cdbcb2cac292a1.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  try {
    (function initSeatWidget() {
      let currentSeats = 32;
      const pricePerSeat = 10;
      const counterEl = document.getElementById('seats-counter-val');
      const totalEl = document.getElementById('seats-total-price');
      const btnMinus = document.getElementById('btn-decrease-seats');
      const btnPlus = document.getElementById('btn-increase-seats');
      const btnApply = document.getElementById('btn-apply-seats');
      function updateDisplay() {
        if (counterEl) counterEl.textContent = currentSeats;
        if (totalEl) totalEl.textContent = '$' + (currentSeats * pricePerSeat).toFixed(2);
      }
      if (btnMinus) {
        btnMinus.addEventListener('click', function () {
          if (currentSeats > 1) {
            currentSeats -= 1;
            updateDisplay();
          }
        });
      }
      if (btnPlus) {
        btnPlus.addEventListener('click', function () {
          if (currentSeats < 250) {
            currentSeats += 1;
            updateDisplay();
          }
        });
      }
      if (btnApply) {
        btnApply.addEventListener('click', function () {
          btnApply.textContent = 'Đang đồng bộ máy chủ...';
          setTimeout(function () {
            btnApply.textContent = '✓ Đã Cập Nhật ' + currentSeats + ' Ghế';
            setTimeout(function () {
              btnApply.textContent = 'Lưu & Cập Nhật Ghế';
            }, 2000);
          }, 500);
        });
      }
    })();
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        alert('Đang tải hóa đơn điện tử VAT (PDF)...');
      },
      /* click */ "1": function (event) {
        alert('Đang tải Chứng Nhận Cấp Phép Bản Quyền Cá Nhân (PDF)...');
      },
    },
  };
});
