// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/e200b7af01a1449a85d689d5b7fbc071.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  try {
    document.addEventListener('DOMContentLoaded', () => {
      // Small click interaction feedback for prompt chips
      const chips = document.querySelectorAll('[data-purpose="ai-assistant-card"] span');
      const aiInput = document.querySelector('[data-purpose="ai-assistant-card"] input');
      chips.forEach(chip => {
        chip.addEventListener('click', () => {
          if (aiInput) {
            aiInput.value = `Gợi ý giải pháp cấu trúc bao bì cho: ${chip.textContent.trim()}`;
            aiInput.focus();
          }
        });
      });
    });
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
    },
  };
});
