// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/2bdc15fac5b0482ca1d7169df1357979.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  try {
    (function () {
      // 1. Tab Switching Architecture (Strictly single-view per category)
      const tabs = [{
        btn: document.getElementById('nav-account'),
        sec: document.getElementById('section-account')
      }, {
        btn: document.getElementById('nav-cad'),
        sec: document.getElementById('section-cad')
      }, {
        btn: document.getElementById('nav-storage'),
        sec: document.getElementById('section-storage')
      }];
      tabs.forEach(({
        btn,
        sec
      }) => {
        if (!btn || !sec) return;
        btn.addEventListener('click', () => {
          tabs.forEach(t => {
            t.btn.classList.remove('bg-white', 'text-on-surface', 'shadow-xs', 'font-semibold');
            t.btn.classList.add('text-stone-600', 'font-medium');
            t.sec.classList.add('hidden');
          });
          btn.classList.remove('text-stone-600', 'font-medium');
          btn.classList.add('bg-white', 'text-on-surface', 'shadow-xs', 'font-semibold');
          sec.classList.remove('hidden');
        });
      });

      // 2. iOS Style Toggle Switch Handler
      function setupToggle(btnId, knobId) {
        const btn = document.getElementById(btnId);
        const knob = document.getElementById(knobId);
        if (!btn || !knob) return;
        let isOn = true;
        btn.addEventListener('click', () => {
          isOn = !isOn;
          btn.setAttribute('aria-pressed', isOn.toString());
          if (isOn) {
            btn.classList.remove('bg-stone-300');
            btn.classList.add('bg-primary');
            knob.classList.add('translate-x-5');
            knob.classList.remove('translate-x-0');
          } else {
            btn.classList.remove('bg-primary');
            btn.classList.add('bg-stone-300');
            knob.classList.remove('translate-x-5');
            knob.classList.add('translate-x-0');
          }
        });
      }
      setupToggle('toggle-cad-grid', 'knob-cad-grid');
      setupToggle('toggle-unbox', 'knob-unbox');
      setupToggle('toggle-cloud', 'knob-cloud');

      // 3. Segmented Pill Handlers
      function setupPillGroup(selector) {
        const pills = document.querySelectorAll(selector);
        pills.forEach(pill => {
          pill.addEventListener('click', () => {
            pills.forEach(p => {
              p.classList.remove('bg-white', 'text-primary', 'shadow-xs', 'font-semibold');
              p.classList.add('text-stone-600');
            });
            pill.classList.remove('text-stone-600');
            pill.classList.add('bg-white', 'text-primary', 'shadow-xs', 'font-semibold');
          });
        });
      }
      setupPillGroup('.unit-opt');
      setupPillGroup('.kfactor-opt');
      setupPillGroup('.format-opt');

      // 4. Save and Reset feedback
      const saveBtn = document.getElementById('btn-save');
      const saveLabel = document.getElementById('save-label');
      function handleSave() {
        if (!saveBtn || !saveLabel) return;
        const originalText = saveLabel.textContent;
        saveLabel.textContent = 'Đã Lưu!';
        saveBtn.classList.add('bg-emerald-200');
        setTimeout(() => {
          saveLabel.textContent = originalText;
          saveBtn.classList.remove('bg-emerald-200');
        }, 1200);
      }
      if (saveBtn) saveBtn.addEventListener('click', handleSave);
      document.addEventListener('keydown', e => {
        if ((e.metaKey || e.ctrlKey) && e.key === 's') {
          e.preventDefault();
          handleSave();
        }
      });

      // Clear cache feedback
      const clearBtn = document.getElementById('btn-clear-cache');
      if (clearBtn) {
        clearBtn.addEventListener('click', () => {
          clearBtn.textContent = 'Đã Dọn Dẹp (0 B)';
          clearBtn.classList.add('text-emerald-700', 'border-emerald-200', 'bg-emerald-50');
        });
      }
    })();
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
    },
  };
});
