// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/d934fa86862742b4a873e9e9fee5126d.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  // Classic scripts publish top-level functions on window.
  window.currentProjectData = currentProjectData;
  window.updateDetailContent = updateDetailContent;
  window.openProjectDetail = openProjectDetail;
  window.closeProjectDetail = closeProjectDetail;
  window.toggleDetailPreview = toggleDetailPreview;
  window.prevProject = prevProject;
  window.nextProject = nextProject;

  let projectsData;
  let currentIdx;
  let isDetailOpen;
  function currentProjectData() {
    return projectsData[currentIdx];
  }
  function updateDetailContent(idx) {
    currentIdx = idx;
    const item = projectsData[currentIdx];
    if (!item) return;
    document.getElementById('detail-hero-img').src = item.image;
    document.getElementById('detail-hero-cat').textContent = item.category;
    document.getElementById('detail-hero-badge').innerHTML = '<span class="material-symbols-outlined text-[13px]">check_circle</span> ' + item.passRate.split(' ')[0] + ' ' + (item.passRate.split(' ')[1] || '');
    document.getElementById('detail-title').textContent = item.name;
    document.getElementById('detail-description').textContent = item.description;

    // Table Key-Values
    document.getElementById('spec-standard').textContent = item.standard;
    document.getElementById('spec-dims').textContent = item.dims;
    document.getElementById('spec-structure').textContent = item.structure;
    document.getElementById('spec-material').textContent = item.material;
    document.getElementById('spec-coating').textContent = item.coating;
    document.getElementById('spec-pass').innerHTML = '<span class="material-symbols-outlined text-[15px]">check_circle</span> ' + item.passRate;
    document.getElementById('spec-history').textContent = item.history;
    document.getElementById('detail-project-counter').textContent = `0${currentIdx + 1} / 0${projectsData.length}`;
    document.getElementById('dock-helper-text').textContent = `${item.name}: Dung sai ${item.tolerance} & ${item.coating}.`;
  }
  function openProjectDetail(index = 0) {
    updateDetailContent(index);
    const carousel = document.getElementById('gallery-carousel-view');
    const detail = document.getElementById('project-detail-view');
    const toggleBtnText = document.getElementById('toggle-view-btn-text');
    carousel.classList.add('opacity-0', 'pointer-events-none');
    setTimeout(() => {
      carousel.classList.add('hidden');
      detail.classList.remove('hidden');
      detail.classList.add('flex');
      isDetailOpen = true;
      if (toggleBtnText) toggleBtnText.textContent = "Xem Dạng Lưới";
    }, 200);
  }
  function closeProjectDetail() {
    const carousel = document.getElementById('gallery-carousel-view');
    const detail = document.getElementById('project-detail-view');
    const toggleBtnText = document.getElementById('toggle-view-btn-text');
    detail.classList.add('hidden');
    detail.classList.remove('flex');
    carousel.classList.remove('hidden', 'opacity-0', 'pointer-events-none');
    isDetailOpen = false;
    if (toggleBtnText) toggleBtnText.textContent = "Xem Dạng Tối Giản";
  }
  function toggleDetailPreview() {
    if (isDetailOpen) {
      closeProjectDetail();
    } else {
      openProjectDetail(currentIdx);
    }
  }
  function prevProject() {
    let prev = currentIdx - 1;
    if (prev < 0) prev = projectsData.length - 1;
    updateDetailContent(prev);
  }
  function nextProject() {
    let next = currentIdx + 1;
    if (next >= projectsData.length) next = 0;
    updateDetailContent(next);
  }

  // Keyboard shortcuts for minimal design navigation (Left/Right to switch, Esc to close)
  try {
    (projectsData = [{
      name: "Âm Dương Nam Châm Luxury",
      category: "Hộp Nam Châm Nắp Gập",
      image: "/stitch/img/42f41003ce34a4a9.jpg",
      standard: "ECMA / FEFCO Caliper Accurate",
      dims: "220 × 150 × 80 mm (Dung sai gân cấn ±0.5mm)",
      structure: "Nắp gập liền đáy tích hợp cặp nam châm vĩnh cửu âm",
      material: "Greyboard 1200g bồi giấy mỹ thuật Cotton 150g",
      coating: "Cán mờ Soft-Touch & Ép kim nhũ vàng 24K",
      passRate: "100/100 Pass (FitCheck™ Auto-Tolerance)",
      history: "10/10/2026 • Chỉnh sửa gần nhất: Hôm nay, 14:20",
      description: "Khuôn hộp cứng cao cấp nắp gập liền đáy tích hợp cặp nam châm vĩnh cửu âm bên trong. Được tùy biến theo tiêu chuẩn bao bì quà tặng sang trọng, gia cố cấn rãnh chính xác 0.5mm cho máy bế định hình tự động.",
      tolerance: "± 0.5 mm"
    }, {
      name: "Bao Diêm Ngăn Kéo (Drawer)",
      category: "Hộp Trượt Kéo Tiện Ích",
      image: "/stitch/img/f958a0d1ac6f013b.jpg",
      standard: "FEFCO 0501 Drawer Slip Case",
      dims: "180 × 110 × 45 mm (Bù cấn rãnh trượt 1.2mm)",
      structure: "Khay trượt 2 đầu có dây ruy-băng kéo ngầm",
      material: "Kraft Nhật 300gsm mộc mạc đanh sợi",
      coating: "In Offset 1 màu đen đậu nành & Cấn gân chuẩn",
      passRate: "Chỉnh dao bế 96% (FitCheck™ Flagged)",
      history: "08/10/2026 • Chỉnh sửa gần nhất: Hôm nay, 11:05",
      description: "Thiết kế dạng bao diêm trượt kéo hai đầu thuận tiện, sử dụng chất liệu Kraft Nhật đanh xơ với khả năng kháng ẩm tốt. Đã tính bù nếp cấn 1.2mm ở mép trượt vỏ bao ngoài.",
      tolerance: "± 0.5 mm"
    }, {
      name: "Túi Đứng Kraft Khóa Zip",
      category: "Bao Bì Mỹ Phẩm & Trà",
      image: "/stitch/img/d274ba3b177d39f3.jpg",
      standard: "FDA & ISO 22000 Barrier Spec",
      dims: "375 × 202 mm (Đáy oval bung nở 60mm)",
      structure: "Túi đáy đứng zipper nhiệt hàn 3 biên cản khí",
      material: "Màng ghép 3 lớp tráng bạc Kraft/AL/PE",
      coating: "Phủ Soft-Touch mờ mịn chống ẩm & Van thở",
      passRate: "100/100 Pass (FitCheck™ Auto-Tolerance)",
      history: "05/10/2026 • Chỉnh sửa gần nhất: Hôm qua, 18:45",
      description: "Túi zipper đáy đứng oval chịu lực, cấu trúc 3 lớp bảo quản tối ưu cho dòng sản phẩm mỹ phẩm organic và thảo mộc khô. Khóa zip nhiệt hàn kín tiêu chuẩn xuất khẩu.",
      tolerance: "± 0.2 mm"
    }, {
      name: "Hộp Gối Uốn Cong (Pillow)",
      category: "Hộp Quà Tự Nhiên Không Keo",
      image: "/stitch/img/1a2b00bef63aaaf6.jpg",
      standard: "ECMA Curve Flap Zero-Glue",
      dims: "160 × 100 × 35 mm (Bán kính cong R50)",
      structure: "Khóa ngàm gấp hai đầu uốn cong không dùng keo",
      material: "Kraft Nâu 280g tái chế 100% Eco-grade",
      coating: "Dập nổi logo chìm & Đường cấn cơ học",
      passRate: "100/100 Pass (FitCheck™ Auto-Tolerance)",
      history: "01/10/2026 • Chỉnh sửa gần nhất: 03/10/2026",
      description: "Đường cấn cong elip mềm mại khép miệng bằng ngàm gập cơ học không cần keo dán. Tiết kiệm 40% thời gian đóng gói và thân thiện 100% với môi trường.",
      tolerance: "± 0.4 mm"
    }]);
    (currentIdx = 0);
    (isDetailOpen = false);
    // Keyboard shortcuts for minimal design navigation (Left/Right to switch, Esc to close)
    window.addEventListener('keydown', e => {
      if (isDetailOpen) {
        if (e.key === 'Escape') closeProjectDetail();
        if (e.key === 'ArrowLeft') prevProject();
        if (e.key === 'ArrowRight') nextProject();
      }
    });
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        document.getElementById('project-carousel').scrollBy({
          left: -380,
          behavior: 'smooth'
        });
      },
      /* click */ "1": function (event) {
        document.getElementById('project-carousel').scrollBy({
          left: 380,
          behavior: 'smooth'
        });
      },
      /* click */ "2": function (event) {
        openProjectDetail(0);
      },
      /* click */ "3": function (event) {
        openProjectDetail(1);
      },
      /* click */ "4": function (event) {
        openProjectDetail(2);
      },
      /* click */ "5": function (event) {
        openProjectDetail(3);
      },
      /* click */ "6": function (event) {
        prevProject();
      },
      /* click */ "7": function (event) {
        nextProject();
      },
      /* click */ "8": function (event) {
        closeProjectDetail();
      },
      /* click */ "9": function (event) {
        window.location.href = '/editor';
      },
      /* click */ "10": function (event) {
        toggleDetailPreview();
      },
      /* click */ "11": function (event) {
        window.location.href = '/editor/step-1';
      },
    },
  };
});
