// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/5d6cc8b46f2640d49209c8b3973f093c.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  // Classic scripts publish top-level functions on window.
  window.triggerToast = triggerToast;
  window.selectMaterial = selectMaterial;

  let activeCardId;
  let searchInput;
  let finishPills;
  let materialCards;
  let gsmSlider;
  let gsmValue;
  let resetFiltersBtn;
  let panelName;
  let panelRating;
  let panelReviews;
  let panelCode;
  let specThickness;
  let specTemp;
  let specPaper;
  let specDie;
  let inspectorSphere;
  let toast;
  let toastMessage;
  function triggerToast(text) {
    if (!toast || !toastMessage) return;
    toastMessage.textContent = text;
    toast.classList.remove('opacity-0', 'translate-y-3');
    toast.classList.add('opacity-100', 'translate-y-0');
    setTimeout(() => {
      toast.classList.add('opacity-0', 'translate-y-3');
      toast.classList.remove('opacity-100', 'translate-y-0');
    }, 2400);
  }

  // Material Selection
  // Material Selection
  function selectMaterial(card) {
    materialCards.forEach(c => {
      c.classList.remove('ring-2', 'ring-[#d4af37]', 'active-card', 'bg-white');
      c.classList.add('bg-white/80');
    });
    card.classList.add('ring-2', 'ring-[#d4af37]', 'active-card', 'bg-white');
    card.classList.remove('bg-white/80');

    // Populate Inspector
    panelName.textContent = card.dataset.name || "Vật Liệu Mẫu";
    panelRating.textContent = card.dataset.rating || "5.0";
    panelReviews.textContent = `(${card.dataset.reviews || '40 bản vẽ'})`;
    panelCode.textContent = card.dataset.code || "#FOIL-PBR";
    specThickness.textContent = card.dataset.thickness || "0.12 mm";
    specTemp.textContent = card.dataset.temp || "130°C";
    specPaper.textContent = card.dataset.paper || "Ivory / Bristol";
    specDie.textContent = card.dataset.die || "Vector Overprint";
    if (card.dataset.gradient) {
      inspectorSphere.style.background = card.dataset.gradient;
    }
    triggerToast(`Đã chọn: ${card.dataset.name}`);
  }
  try {
    (activeCardId = "mat-1");
    (searchInput = document.getElementById('searchInput'));
    (finishPills = document.querySelectorAll('.finish-pill'));
    (materialCards = document.querySelectorAll('.material-card'));
    (gsmSlider = document.getElementById('gsmSlider'));
    (gsmValue = document.getElementById('gsmValue'));
    (resetFiltersBtn = document.getElementById('resetFiltersBtn'));
    (panelName = document.getElementById('panelName'));
    (panelRating = document.getElementById('panelRating'));
    (panelReviews = document.getElementById('panelReviews'));
    (panelCode = document.getElementById('panelCode'));
    (specThickness = document.getElementById('specThickness'));
    (specTemp = document.getElementById('specTemp'));
    (specPaper = document.getElementById('specPaper'));
    (specDie = document.getElementById('specDie'));
    (inspectorSphere = document.getElementById('inspectorSphere'));
    (toast = document.getElementById('toastNotification'));
    (toastMessage = document.getElementById('toastMessage'));
    materialCards.forEach(card => {
      card.addEventListener('click', e => {
        if (e.target.closest('.favorite-btn')) {
          e.stopPropagation();
          const favIcon = e.target.closest('.favorite-btn').querySelector('.material-symbols-outlined');
          const isFilled = favIcon.style.fontVariationSettings?.includes("'FILL' 1");
          if (isFilled) {
            favIcon.style.fontVariationSettings = "'FILL' 0";
            e.target.closest('.favorite-btn').classList.remove('text-red-500');
            e.target.closest('.favorite-btn').classList.add('text-stone-300');
            triggerToast('Đã bỏ khỏi danh sách yêu thích');
          } else {
            favIcon.style.fontVariationSettings = "'FILL' 1";
            e.target.closest('.favorite-btn').classList.add('text-red-500');
            e.target.closest('.favorite-btn').classList.remove('text-stone-300');
            triggerToast('Đã lưu vào bộ sưu tập mẫu');
          }
          return;
        }
        selectMaterial(card);
      });
    });

    // Category Filter Pills
    // Category Filter Pills
    finishPills.forEach(pill => {
      pill.addEventListener('click', () => {
        finishPills.forEach(p => {
          p.classList.remove('bg-white', 'text-stone-900', 'shadow-2xs');
          p.classList.add('text-stone-500');
        });
        pill.classList.add('bg-white', 'text-stone-900', 'shadow-2xs');
        pill.classList.remove('text-stone-500');
        const cat = pill.dataset.category;
        materialCards.forEach(card => {
          if (cat === 'all' || card.dataset.cat === cat) {
            card.style.display = 'flex';
          } else {
            card.style.display = 'none';
          }
        });
      });
    });

    // GSM Slider
    // GSM Slider
    gsmSlider?.addEventListener('input', e => {
      gsmValue.textContent = `180 - ${e.target.value} gsm`;
    });

    // Search filter
    // Search filter
    searchInput?.addEventListener('input', e => {
      const q = e.target.value.toLowerCase().trim();
      materialCards.forEach(card => {
        const text = (card.dataset.name + " " + card.dataset.code + " " + card.dataset.spec).toLowerCase();
        if (text.includes(q)) {
          card.style.display = 'flex';
        } else {
          card.style.display = 'none';
        }
      });
    });

    // Keyboard shortcut Cmd/Ctrl + K
    // Keyboard shortcut Cmd/Ctrl + K
    window.addEventListener('keydown', e => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault();
        searchInput?.focus();
      }
    });

    // Reset Filters
    // Reset Filters
    resetFiltersBtn?.addEventListener('click', () => {
      if (searchInput) searchInput.value = '';
      if (gsmSlider) {
        gsmSlider.value = 450;
        gsmValue.textContent = '180 - 450 gsm';
      }
      finishPills[0]?.click();
      materialCards.forEach(card => card.style.display = 'flex');
      triggerToast('Đã đặt lại toàn bộ bộ lọc');
    });

    // Inspector Action Buttons
    // Inspector Action Buttons
    document.getElementById('apply3dBtn')?.addEventListener('click', () => {
      triggerToast(`Đang nạp ${panelName.textContent} vào không gian WrapFit 3D Studio...`);
    });
    document.getElementById('customizeShaderBtn')?.addEventListener('click', () => {
      triggerToast('Mở bảng điều chỉnh thông số Shader PBR (Roughness, Metallic, Anisotropy)...');
    });
    document.getElementById('closeInspectorBtn')?.addEventListener('click', () => {
      triggerToast('Đã thu gọn bảng chi tiết vật liệu.');
    });
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
    },
  };
});
