// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/9453d3217514482d8c12036305d3c024.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  try {
    (function () {
      const pills = document.querySelectorAll('.filter-pill');
      const cards = document.querySelectorAll('#projectsGrid article');
      pills.forEach(pill => {
        pill.addEventListener('click', () => {
          const filter = pill.getAttribute('data-filter');
          pills.forEach(p => {
            p.classList.remove('bg-surface-container-lowest', 'text-primary', 'shadow-sm', 'font-semibold');
            p.classList.add('text-on-surface-variant');
          });
          pill.classList.add('bg-surface-container-lowest', 'text-primary', 'shadow-sm', 'font-semibold');
          pill.classList.remove('text-on-surface-variant');
          cards.forEach(card => {
            const status = card.getAttribute('data-status');
            if (filter === 'all' || status === filter) {
              card.style.display = 'flex';
            } else {
              card.style.display = 'none';
            }
          });
        });
      });
    })();
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
    },
  };
});
