// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/64ae8cc2065f4cada9892a1fcd1a0dc1.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  // Classic scripts publish top-level functions on window.
  window.notify = notify;
  window.switchVisual = switchVisual;
  window.copyUnboxLink = copyUnboxLink;
  window.triggerExport = triggerExport;
  window.triggerShare = triggerShare;

  let cut;
  let crease;
  let bleed;
  let safe;
  let toast;
  let toastMsg;
  function notify(text) {
    toastMsg.innerText = text;
    toast.classList.remove('-translate-y-6', 'opacity-0');
    toast.classList.add('translate-y-0', 'opacity-100');
    setTimeout(() => {
      toast.classList.remove('translate-y-0', 'opacity-100');
      toast.classList.add('-translate-y-6', 'opacity-0');
    }, 2400);
  }
  function switchVisual(mode) {
    document.querySelectorAll('.layer-pill').forEach(btn => {
      btn.className = 'layer-pill px-2.5 py-1 rounded-full text-[11px] font-medium text-neutral-500 hover:text-neutral-900 hover:bg-black/5 transition-all';
    });
    if (mode === 'all') {
      document.getElementById('mode-cad').className = 'layer-pill px-2.5 py-1 rounded-full text-[11px] font-medium bg-neutral-900 text-white transition-all';
      cut.style.opacity = '1';
      crease.style.opacity = '1';
      bleed.style.opacity = '0.75';
      safe.style.opacity = '1';
    } else if (mode === 'cut') {
      document.getElementById('mode-cut').className = 'layer-pill px-2.5 py-1 rounded-full text-[11px] font-medium bg-neutral-900 text-white transition-all';
      cut.style.opacity = '1';
      crease.style.opacity = '0.08';
      bleed.style.opacity = '0.05';
      safe.style.opacity = '0.05';
    } else if (mode === 'crease') {
      document.getElementById('mode-crease').className = 'layer-pill px-2.5 py-1 rounded-full text-[11px] font-medium bg-neutral-900 text-white transition-all';
      cut.style.opacity = '0.1';
      crease.style.opacity = '1';
      bleed.style.opacity = '0.05';
      safe.style.opacity = '0.05';
    }
  }
  function copyUnboxLink() {
    navigator.clipboard?.writeText('https://wrapfit.studio/unboxing/wf-2024-c92');
    notify('Đã sao chép link Unboxing AR!');
  }
  function triggerExport(type) {
    notify(`Đang tải trọn bộ hồ sơ ${type.toUpperCase()}...`);
  }
  function triggerShare() {
    notify('Đang gửi dữ liệu đến xưởng in đối tác...');
  }
  try {
    (cut = document.getElementById('dieline-cut'));
    (crease = document.getElementById('dieline-crease'));
    (bleed = document.getElementById('dieline-bleed'));
    (safe = document.getElementById('dieline-safe'));
    (toast = document.getElementById('toast'));
    (toastMsg = document.getElementById('toast-msg'));
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        switchVisual('all');
      },
      /* click */ "1": function (event) {
        switchVisual('cut');
      },
      /* click */ "2": function (event) {
        switchVisual('crease');
      },
      /* click */ "3": function (event) {
        copyUnboxLink();
      },
      /* click */ "4": function (event) {
        triggerExport('zip');
      },
      /* click */ "5": function (event) {
        triggerExport('pdf');
      },
      /* click */ "6": function (event) {
        triggerExport('dxf');
      },
      /* click */ "7": function (event) {
        triggerExport('3d');
      },
      /* click */ "8": function (event) {
        triggerShare();
      },
    },
  };
});
