// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/d49107077c4245a2bfb98fa622de346e.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  // Classic scripts publish top-level functions on window.
  window.selectMaterial = selectMaterial;
  window.scrollCarousel = scrollCarousel;
  window.filterCategory = filterCategory;

  let materialsData;
  function selectMaterial(index) {
    const data = materialsData[index];
    if (!data) return;

    // Update card visual active ring
    const cards = document.querySelectorAll('.material-card');
    cards.forEach((c, idx) => {
      if (idx === index) {
        c.classList.remove('border-transparent', 'hover:border-burgundy/40');
        c.classList.add('border-burgundy', 'scale-[1.02]');
      } else {
        c.classList.remove('border-burgundy', 'scale-[1.02]');
        c.classList.add('border-transparent', 'hover:border-burgundy/40');
      }
    });

    // Smooth fade transition on Hero Section
    const bgImg = document.getElementById('heroBgImage');
    const title = document.getElementById('heroTitle');
    const subtitle = document.getElementById('heroSubtitle');
    const desc = document.getElementById('heroDescription');
    const specGsm = document.getElementById('specGsm');
    const specCaliper = document.getElementById('specCaliper');
    const specPrice = document.getElementById('specPrice');
    const packyAdvice = document.getElementById('packyAdvice');
    const quickBadge = document.getElementById('quickBadge');
    bgImg.style.opacity = '0.3';
    title.style.opacity = '0.4';
    desc.style.opacity = '0.4';
    setTimeout(() => {
      bgImg.style.backgroundImage = `url('${data.bgUrl}')`;
      title.innerText = data.title;
      subtitle.innerText = data.subtitle;
      desc.innerText = data.description;
      specGsm.innerText = data.gsm;
      specCaliper.innerText = data.caliper;
      specPrice.innerText = data.price;
      packyAdvice.innerHTML = data.packyText;
      if (quickBadge) quickBadge.innerText = `Substrate #${data.id}`;
      bgImg.style.opacity = '0.95';
      title.style.opacity = '1';
      desc.style.opacity = '1';
    }, 200);
  }
  function scrollCarousel(direction) {
    const track = document.getElementById('cardsTrack');
    const scrollAmount = 260 * direction;
    track.scrollBy({
      left: scrollAmount,
      behavior: 'smooth'
    });
  }
  function filterCategory(cat, btn) {
    const filterBtns = document.querySelectorAll('.filter-btn');
    filterBtns.forEach(b => {
      b.classList.remove('bg-burgundy', 'text-white', 'shadow-md');
      b.classList.add('bg-white', 'text-on-surface-variant', 'border', 'border-black/5');
    });
    btn.classList.add('bg-burgundy', 'text-white', 'shadow-md');
    btn.classList.remove('bg-white', 'text-on-surface-variant', 'border', 'border-black/5');
    if (cat === 'all') selectMaterial(0);else if (cat === 'finepaper') selectMaterial(0);else if (cat === 'kraft') selectMaterial(1);else if (cat === 'greyboard') selectMaterial(2);else if (cat === 'foil') selectMaterial(4);
  }
  try {
    (materialsData = [{
      id: "MF-01",
      title: "Giấy Mỹ Thuật Kẹp Bông",
      subtitle: "VẬT LIỆU CAO CẤP / SUBSTRATE ARCHIVE",
      description: "Tactile Cotton 350 GSM • 100% Virgin Cotton Pulp • Bề mặt xốp mịn sang trọng hấp thụ hoàn hảo lực dập và ép kim sâu.",
      gsm: "350 g/m²",
      caliper: "Caliper: 0.42mm (420µm)",
      price: "14.800 ₫ / sheet (79×109cm)",
      bgUrl: "/stitch/img/d4747bd7fbdff9e6.jpg",
      packyText: "Vật liệu <strong class='text-on-surface font-semibold'>Giấy Kẹp Bông 350 GSM</strong> hoàn hảo cho hộp cứng Luxury. Nhớ bù dung sai cấn rãnh <span class='font-mono font-bold text-burgundy'>+0.30mm</span> trên dieline nhé!"
    }, {
      id: "KR-02",
      title: "Kraft Tái Sinh Mộc Nâu",
      subtitle: "ECO PACKAGING / SUSTAINABLE SERIE",
      description: "Kraft Unbleached 300 GSM • 100% sợi gỗ thông tái chế tự nhiên • Thớ vân mộc mạc, độ dẻo dai và kháng rách vượt trội.",
      gsm: "300 g/m²",
      caliper: "Caliper: 0.38mm (380µm)",
      price: "7.200 ₫ / sheet (79×109cm)",
      bgUrl: "/stitch/img/475326f160122011.jpg",
      packyText: "Chất liệu <strong class='text-on-surface font-semibold'>Kraft Mộc Nâu</strong> thấm hút mực rất tốt, thích hợp in lụa 1 màu hoặc ép nhũ kim loại trắng/đen mờ!"
    }, {
      id: "GB-03",
      title: "Carton Lạnh Greyboard Cực Nén",
      subtitle: "RIGID STRUCTURE / LUXURY CORE",
      description: "High-density Greyboard 1400 GSM • Caliper dày dặn 2.0mm • Khung xương chuẩn xác chống cong vênh tuyệt đối cho hộp quà thượng lưu.",
      gsm: "1400 g/m²",
      caliper: "Caliper: 2.00mm (2000µm)",
      price: "18.500 ₫ / sheet (80×120cm)",
      bgUrl: "/stitch/img/adfac02232d0a694.jpg",
      packyText: "Khung <strong class='text-on-surface font-semibold'>Carton Lạnh 2.0mm</strong> cần phay rãnh chữ V góc 90° hoặc 120° để mép hộp sắc cạnh không bị phồng bọc giấy."
    }, {
      id: "CV-04",
      title: "Couche Velvet Soft-Touch Đen",
      subtitle: "SILKY COATED / MODERN CONTRAST",
      description: "Couche Matt 300 GSM phủ màng nhung Soft-Touch chống xước • Màu đen tuyền sâu thẳm, tương phản rực rỡ với ép kim vàng & bạc.",
      gsm: "300 g/m²",
      caliper: "Caliper: 0.31mm (310µm)",
      price: "9.800 ₫ / sheet (65×86cm)",
      bgUrl: "/stitch/img/207b24419918b8c2.jpg",
      packyText: "<strong class='text-on-surface font-semibold'>Couche Velvet Đen</strong> tôn nét nhũ kim 22K đỉnh cao! Dùng khuôn đồng khắc vi tính để chi tiết nhũ sắc sảo nhất."
    }, {
      id: "HF-05",
      title: "Hot Foil Ép Kim Vàng 22K Kurz",
      subtitle: "FOIL STAMPING / LUXOR ARCHIVE",
      description: "Kurz Luxor 428 Metallic Foil • Độ bám dính A+ trên nền giấy mỹ thuật xốp • Ánh kim vàng kim hoàng gia không ố mờ theo thời gian.",
      gsm: "Film Base 12µm",
      caliper: "Độ mảnh nét: 0.15mm",
      price: "Nhiệt dập: 130°C - 145°C",
      bgUrl: "/stitch/img/eb41c91d3eda5b94.jpg",
      packyText: "Nhiệt dập chuẩn của <strong class='text-on-surface font-semibold'>Kurz 428</strong> là 135°C. Thời gian ép giữ 0.4 giây đảm bảo không bị lem viền nét chữ thanh mảnh."
    }]);
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        filterCategory('all', this);
      },
      /* click */ "1": function (event) {
        filterCategory('finepaper', this);
      },
      /* click */ "2": function (event) {
        filterCategory('kraft', this);
      },
      /* click */ "3": function (event) {
        filterCategory('greyboard', this);
      },
      /* click */ "4": function (event) {
        filterCategory('foil', this);
      },
      /* click */ "5": function (event) {
        scrollCarousel(-1);
      },
      /* click */ "6": function (event) {
        selectMaterial(0);
      },
      /* click */ "7": function (event) {
        selectMaterial(1);
      },
      /* click */ "8": function (event) {
        selectMaterial(2);
      },
      /* click */ "9": function (event) {
        selectMaterial(3);
      },
      /* click */ "10": function (event) {
        selectMaterial(4);
      },
      /* click */ "11": function (event) {
        scrollCarousel(1);
      },
    },
  };
});
