// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/583071fa9dec46e9884ca06cbdef850c.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  // Classic scripts publish top-level functions on window.
  window.updateBoxTransform = updateBoxTransform;
  window.applyFoldState = applyFoldState;
  window.setFoldPercent = setFoldPercent;
  window.activateFlatMode = activateFlatMode;
  window.activate3DMode = activate3DMode;
  window.activateUnboxMode = activateUnboxMode;
  window.closeAllPopovers = closeAllPopovers;
  window.updateTitle = updateTitle;
  window.applyMaterial = applyMaterial;
  window.flashExportNotification = flashExportNotification;

  let viewport;
  let cartonBox;
  let studioShadow;
  let foldSlider;
  let foldPercentDisplay;
  let dragHint;
  let jointLeft;
  let jointBack;
  let jointRight;
  let jointGlue;
  let jointTop;
  let jointTuck;
  let jointBottom;
  let jointDustLeftTop;
  let jointDustLeftBottom;
  let jointDustRightTop;
  let jointDustRightBottom;
  let isDragging;
  let previousMousePosition;
  let rotX;
  let rotY;
  let zoomLevel;
  let isFlatMode;
  function updateBoxTransform() {
    if (isFlatMode) {
      cartonBox.style.transform = `scale(${zoomLevel * 0.85}) rotateX(0deg) rotateY(0deg) rotateZ(0deg)`;
    } else {
      cartonBox.style.transform = `scale(${zoomLevel}) rotateX(${rotX}deg) rotateY(${rotY}deg) rotateZ(0deg)`;
    }
  }

  // Mouse Orbit Controls
  // ================= ORIGAMI FOLDING ENGINE =================
  function applyFoldState(val, openLidAngle = 0) {
    const ratio = Math.max(0, Math.min(100, val)) / 100;
    foldPercentDisplay.textContent = `${Math.round(val)}%`;

    // Angles based on fold progress
    const sideAngle = 90 * ratio;
    const glueAngle = 90 * ratio;
    const tuckLidAngle = openLidAngle > 0 ? (90 - openLidAngle) * ratio : 90 * ratio;
    const tuckTabAngle = openLidAngle > 0 ? 30 * ratio : 90 * ratio;
    const bottomAngle = 90 * ratio;
    const dustAngle = 85 * ratio;

    // Apply 3D transforms to hierarchical joints
    jointLeft.style.transform = `rotateY(${-sideAngle}deg)`;
    jointBack.style.transform = `rotateY(${-sideAngle}deg)`;
    jointRight.style.transform = `rotateY(${-sideAngle}deg)`;
    jointGlue.style.transform = `rotateY(${-glueAngle}deg)`;
    jointTop.style.transform = `rotateX(${tuckLidAngle}deg)`;
    jointTuck.style.transform = `rotateX(${tuckTabAngle}deg)`;
    jointBottom.style.transform = `rotateX(${-bottomAngle}deg)`;
    if (jointDustLeftTop) jointDustLeftTop.style.transform = `rotateX(${dustAngle}deg)`;
    if (jointDustLeftBottom) jointDustLeftBottom.style.transform = `rotateX(${-dustAngle}deg)`;
    if (jointDustRightTop) jointDustRightTop.style.transform = `rotateX(${dustAngle}deg)`;
    if (jointDustRightBottom) jointDustRightBottom.style.transform = `rotateX(${-dustAngle}deg)`;

    // Shadow diffusion reacts to folding
    studioShadow.style.opacity = `${0.2 + ratio * 0.8}`;
    studioShadow.style.transform = `translateY(${120 - ratio * 20}px) scale(${0.8 + ratio * 0.4}) rotateX(85deg)`;
  }
  function setFoldPercent(pct, openLid = 0) {
    foldSlider.value = pct;
    applyFoldState(pct, openLid);
  }

  // Presets
  let btnPresetFlat;
  let btnPresetBox;
  let btnPresetUnbox;
  let mode3dBtn;
  let mode2dBtn;
  let openLidBtn;
  function activateFlatMode() {
    isFlatMode = true;
    setFoldPercent(0);
    rotX = 0;
    rotY = 0;
    updateBoxTransform();
    mode2dBtn.classList.add('bg-neutral-900', 'text-white');
    mode2dBtn.classList.remove('text-neutral-600');
    mode3dBtn.classList.remove('bg-neutral-900', 'text-white');
    mode3dBtn.classList.add('text-neutral-600');
    dragHint.innerHTML = `<span class="text-primary font-bold">2D DIELINE CAD VIEW:</span> Bản vẽ kỹ thuật trải phẳng dao bế chuẩn FEFCO 0215 (Nét dao Cut: Xanh · Cấn Crease: Đỏ · Tai Glue: Ngọc)`;
    flashExportNotification('Đã xả phẳng 2D dieline kỹ thuật (1:1 CAD Sheet)');
  }
  function activate3DMode() {
    isFlatMode = false;
    setFoldPercent(100);
    rotX = -20;
    rotY = 32;
    updateBoxTransform();
    mode3dBtn.classList.add('bg-neutral-900', 'text-white');
    mode3dBtn.classList.remove('text-neutral-600');
    mode2dBtn.classList.remove('bg-neutral-900', 'text-white');
    mode2dBtn.classList.add('text-neutral-600');
    dragHint.innerHTML = `<svg class="w-3.5 h-3.5 text-primary animate-pulse stroke-current fill-none stroke-[2]" viewBox="0 0 24 24"><path d="M18 11V6a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v0"></path><path d="M14 10V4a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v2"></path><path d="M10 10.5V6a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v8"></path><path d="M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15"></path></svg> <span>Kéo chuột để xoay 3D Orbit · Kéo thanh trượt đáy để gập/mở nắp CAD Dieline chuẩn FEFCO 0215</span>`;
  }
  function activateUnboxMode() {
    isFlatMode = false;
    rotX = -12;
    rotY = 28;
    updateBoxTransform();
    setFoldPercent(95, 50); // lid opened 50 degrees
    mode3dBtn.classList.add('bg-neutral-900', 'text-white');
    mode2dBtn.classList.remove('bg-neutral-900', 'text-white');
    flashExportNotification('Phối cảnh Unboxing: Nắp mở 45° kiểm tra khớp gài');
  }
  let toolBtns;
  let toolPanels;
  let activeToolKey;
  function closeAllPopovers() {
    toolPanels.forEach(panel => panel.classList.add('hidden'));
    toolBtns.forEach(btn => {
      btn.classList.remove('bg-primary', 'text-white');
      if (btn.dataset.tool === 'select') {
        btn.classList.add('bg-white/25');
      }
    });
    activeToolKey = null;
  }
  // Typography Update function
  function updateTitle() {
    const val = document.getElementById('inputBoxTitle').value.trim();
    if (val) {
      document.getElementById('boxTitle').textContent = val;
      flashExportNotification(`Đã cập nhật typography: "${val}"`);
    }
  }

  // Material Switcher
  let matSelectors;
  let allFaces;
  let inspectorMatName;
  let spherePreview;
  let materialDb;
  function applyMaterial(key) {
    const mat = materialDb[key];
    if (!mat) return;
    inspectorMatName.textContent = mat.name;
    spherePreview.style.cssText = mat.sphereBg;
    allFaces.forEach(face => {
      if (face.id !== 'panelGlue') {
        face.classList.remove('mat-cotton', 'mat-kraft', 'mat-greyboard');
        face.classList.add(mat.className);
      }
    });
    matSelectors.forEach(btn => {
      if (btn.dataset.substrate === key) {
        btn.className = 'mat-selector-btn py-1 px-1.5 rounded-lg text-[9px] font-mono border border-primary bg-white/20 text-white font-medium';
      } else {
        btn.className = 'mat-selector-btn py-1 px-1.5 rounded-lg text-[9px] font-mono border border-white/10 text-stone-400 hover:text-white';
      }
    });
  }
  let foilActive;
  let foilEmblem;
  let boxTitleEl;
  let toggleGoldFoil;
  // Floating Notification Toast Function
  function flashExportNotification(msg) {
    const toast = document.createElement('div');
    toast.className = 'fixed top-16 left-1/2 -translate-x-1/2 z-50 glass-dock-dark text-white px-4 py-2 rounded-full text-xs font-mono tracking-wide shadow-xl flex items-center gap-2 border border-white/20 transition-all pointer-events-none';
    toast.innerHTML = `<span class="w-2 h-2 rounded-full bg-sky-400 animate-ping"></span> <span>${msg}</span>`;
    document.body.appendChild(toast);
    setTimeout(() => {
      toast.style.opacity = '0';
      setTimeout(() => toast.remove(), 300);
    }, 2400);
  }
  try {
    (viewport = document.getElementById('viewportContainer'));
    (cartonBox = document.getElementById('cartonBox'));
    (studioShadow = document.getElementById('studioShadow'));
    (foldSlider = document.getElementById('foldSlider'));
    (foldPercentDisplay = document.getElementById('foldPercentDisplay'));
    (dragHint = document.getElementById('dragHint'));
    (jointLeft = document.getElementById('jointLeft'));
    (jointBack = document.getElementById('jointBack'));
    (jointRight = document.getElementById('jointRight'));
    (jointGlue = document.getElementById('jointGlue'));
    (jointTop = document.getElementById('jointTop'));
    (jointTuck = document.getElementById('jointTuck'));
    (jointBottom = document.getElementById('jointBottom'));
    (jointDustLeftTop = document.getElementById('jointDustLeftTop'));
    (jointDustLeftBottom = document.getElementById('jointDustLeftBottom'));
    (jointDustRightTop = document.getElementById('jointDustRightTop'));
    (jointDustRightBottom = document.getElementById('jointDustRightBottom'));
    (isDragging = false);
    (previousMousePosition = {
      x: 0,
      y: 0
    });
    (rotX = -20);
    (rotY = 32);
    (zoomLevel = 1.0);
    (isFlatMode = false);
    // Mouse Orbit Controls
    viewport.addEventListener('mousedown', e => {
      if (e.target.closest('button') || e.target.closest('input') || e.target.closest('aside') || e.target.closest('header') || e.target.closest('footer')) return;
      isDragging = true;
      previousMousePosition = {
        x: e.clientX,
        y: e.clientY
      };
    });
    window.addEventListener('mousemove', e => {
      if (!isDragging) return;
      const deltaX = e.clientX - previousMousePosition.x;
      const deltaY = e.clientY - previousMousePosition.y;
      rotY += deltaX * 0.45;
      rotX -= deltaY * 0.45;
      rotX = Math.max(-85, Math.min(85, rotX));
      if (isFlatMode && (Math.abs(deltaX) > 2 || Math.abs(deltaY) > 2)) {
        isFlatMode = false;
        document.getElementById('mode3dBtn').classList.add('bg-neutral-900', 'text-white');
        document.getElementById('mode2dBtn').classList.remove('bg-neutral-900', 'text-white');
      }
      updateBoxTransform();
      previousMousePosition = {
        x: e.clientX,
        y: e.clientY
      };
    });
    window.addEventListener('mouseup', () => {
      isDragging = false;
    });

    // Touch Support
    // Touch Support
    viewport.addEventListener('touchstart', e => {
      if (e.touches.length === 1 && !e.target.closest('button') && !e.target.closest('input')) {
        isDragging = true;
        previousMousePosition = {
          x: e.touches[0].clientX,
          y: e.touches[0].clientY
        };
      }
    }, {
      passive: true
    });
    window.addEventListener('touchmove', e => {
      if (!isDragging || e.touches.length !== 1) return;
      const deltaX = e.touches[0].clientX - previousMousePosition.x;
      const deltaY = e.touches[0].clientY - previousMousePosition.y;
      rotY += deltaX * 0.5;
      rotX -= deltaY * 0.5;
      rotX = Math.max(-85, Math.min(85, rotX));
      updateBoxTransform();
      previousMousePosition = {
        x: e.touches[0].clientX,
        y: e.touches[0].clientY
      };
    }, {
      passive: true
    });
    window.addEventListener('touchend', () => {
      isDragging = false;
    });

    // Zoom on Wheel
    // Zoom on Wheel
    viewport.addEventListener('wheel', e => {
      e.preventDefault();
      zoomLevel -= e.deltaY * 0.001;
      zoomLevel = Math.max(0.55, Math.min(1.85, zoomLevel));
      updateBoxTransform();
    }, {
      passive: false
    });

    // Zoom buttons
    // Zoom buttons
    document.getElementById('zoomOutBtn').addEventListener('click', () => {
      if (zoomLevel > 0.6) {
        zoomLevel -= 0.12;
        updateBoxTransform();
      }
    });
    document.getElementById('zoomInBtn').addEventListener('click', () => {
      if (zoomLevel < 1.7) {
        zoomLevel += 0.12;
        updateBoxTransform();
      }
    });

    // ================= ORIGAMI FOLDING ENGINE =================
    foldSlider.addEventListener('input', e => {
      applyFoldState(parseFloat(e.target.value));
    });
    (btnPresetFlat = document.getElementById('btnPresetFlat'));
    (btnPresetBox = document.getElementById('btnPresetBox'));
    (btnPresetUnbox = document.getElementById('btnPresetUnbox'));
    (mode3dBtn = document.getElementById('mode3dBtn'));
    (mode2dBtn = document.getElementById('mode2dBtn'));
    (openLidBtn = document.getElementById('openLidBtn'));
    btnPresetFlat.addEventListener('click', activateFlatMode);
    mode2dBtn.addEventListener('click', activateFlatMode);
    btnPresetBox.addEventListener('click', activate3DMode);
    mode3dBtn.addEventListener('click', activate3DMode);
    btnPresetUnbox.addEventListener('click', activateUnboxMode);
    openLidBtn.addEventListener('click', activateUnboxMode);

    // Initialize at 95% fold
    // Initialize at 95% fold
    applyFoldState(95);

    // LEFT TOOLBAR POPOVERS INTERACTION
    (toolBtns = document.querySelectorAll('.tool-btn'));
    (toolPanels = document.querySelectorAll('.tool-panel'));
    (activeToolKey = null);
    toolBtns.forEach(btn => {
      btn.addEventListener('click', e => {
        e.stopPropagation();
        const toolKey = btn.dataset.tool;
        if (activeToolKey === toolKey) {
          closeAllPopovers();
          return;
        }
        toolPanels.forEach(p => p.classList.add('hidden'));
        toolBtns.forEach(b => b.classList.remove('bg-primary', 'text-white'));
        const targetPanel = document.getElementById(`panel-${toolKey}`);
        if (targetPanel) {
          targetPanel.classList.remove('hidden');
          btn.classList.add('bg-primary', 'text-white');
          activeToolKey = toolKey;
        }
      });
    });
    document.addEventListener('click', e => {
      if (!e.target.closest('#toolPopoverContainer') && !e.target.closest('.tool-btn')) {
        closeAllPopovers();
      }
    });

    // Typography Update function
    (matSelectors = document.querySelectorAll('.mat-selector-btn'));
    (allFaces = document.querySelectorAll('.panel-face'));
    (inspectorMatName = document.getElementById('inspectorMatName'));
    (spherePreview = document.getElementById('spherePreview'));
    (materialDb = {
      cotton: {
        name: 'Cotton Ivory 350G',
        className: 'mat-cotton',
        sphereBg: 'background: radial-gradient(circle at 30% 28%, #ffffff 0%, #ede8de 45%, #b2ab9c 90%); box-shadow: inset -5px -5px 12px rgba(0,0,0,0.4), inset 3px 3px 8px rgba(255,255,255,0.9), 0 10px 24px -4px rgba(0,0,0,0.5);'
      },
      kraft: {
        name: 'Kraft Nâu Mộc 300G',
        className: 'mat-kraft',
        sphereBg: 'background: radial-gradient(circle at 30% 28%, #edd3b2 0%, #cbb08c 45%, #7e5a35 90%); box-shadow: inset -5px -5px 12px rgba(0,0,0,0.5), inset 2px 2px 6px rgba(255,255,255,0.6), 0 10px 24px -4px rgba(0,0,0,0.5);'
      },
      greyboard: {
        name: 'Bìa Cứng Greyboard 1200G',
        className: 'mat-greyboard',
        sphereBg: 'background: radial-gradient(circle at 30% 28%, #5a5d64 0%, #2e3136 50%, #111215 90%); box-shadow: inset -5px -5px 14px rgba(0,0,0,0.8), inset 2px 2px 8px rgba(255,255,255,0.3), 0 10px 24px -4px rgba(0,0,0,0.7);'
      }
    });
    matSelectors.forEach(btn => btn.addEventListener('click', () => applyMaterial(btn.dataset.substrate)));

    // Foil & Special Effects
    (foilActive = true);
    (foilEmblem = document.getElementById('foilEmblem'));
    (boxTitleEl = document.getElementById('boxTitle'));
    (toggleGoldFoil = document.getElementById('toggleGoldFoil'));
    toggleGoldFoil.addEventListener('click', () => {
      foilActive = !foilActive;
      if (foilActive) {
        boxTitleEl.classList.add('gold-foil-text');
        foilEmblem.classList.add('gold-foil-border');
        toggleGoldFoil.classList.add('bg-amber-500/20', 'text-amber-300', 'border-amber-500/40');
        document.getElementById('inspectorFinishName').textContent = 'Ép Kim Gold Foil 22K';
        flashExportNotification('Đã kích hoạt ép kim vàng dập nổi 22K');
      } else {
        boxTitleEl.classList.remove('gold-foil-text');
        foilEmblem.classList.remove('gold-foil-border');
        toggleGoldFoil.classList.remove('bg-amber-500/20', 'text-amber-300', 'border-amber-500/40');
        document.getElementById('inspectorFinishName').textContent = 'In Mộc Chuẩn Offset';
        flashExportNotification('Đã chuyển sang in mực Offset tiêu chuẩn');
      }
    });

    // Snapshot Render Button
    // Snapshot Render Button
    document.getElementById('snapshotRenderBtn').addEventListener('click', () => {
      flashExportNotification('Đã kết xuất ảnh Render 4K Studio (3840 × 2160 PBR)');
    });

    // Floating Notification Toast Function
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        flashExportNotification('Đã xuất bản vẽ DXF Vector 1:1');
        return false;
      },
      /* click */ "1": function (event) {
        flashExportNotification('Đã xuất file PDF In Offset CMYK');
        return false;
      },
      /* click */ "2": function (event) {
        flashExportNotification('Đã xuất mô hình GLTF 3D Texture');
        return false;
      },
      /* click */ "3": function (event) {
        flashExportNotification('Đã tạo đơn đặt hàng in mẫu Proofing (Số lượng: 03 hộp test)');
      },
      /* click */ "4": function (event) {
        flashExportNotification('Đã cập nhật thông số bế kỹ thuật');
        closeAllPopovers();
      },
      /* click */ "5": function (event) {
        flashExportNotification('Đã tải lên vector logo Atelier');
      },
      /* click */ "6": function (event) {
        updateTitle();
        closeAllPopovers();
      },
      /* click */ "7": function (event) {
        setFoldPercent(0);
      },
      /* click */ "8": function (event) {
        setFoldPercent(100);
      },
      /* click */ "9": function (event) {
        flashExportNotification('Đã kích hoạt chế độ render chất lượng cao không mờ hình');
      },
    },
  };
});
