// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/1c24590034664885b91471cffe4c0d75.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';
import * as THREE_NAMESPACE from 'three';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;
  const THREE = scope.useThree(THREE_NAMESPACE);

  try {
    (function () {
      const container = document.getElementById('threejs-container-ANIMATION_122');
      const devicePixelRatio = window.devicePixelRatio || 1;
      // Three.js Interactive Precision Packaging Workbench
      (function () {
        const containerEl = typeof container !== 'undefined' && container ? container : document.getElementById('threejs-container') || document.body;
        while (containerEl.firstChild) {
          containerEl.removeChild(containerEl.firstChild);
        }
        const width = containerEl.clientWidth || window.innerWidth || 1440;
        const height = containerEl.clientHeight || window.innerHeight || 900;
        const scene = new THREE.Scene();
        // Warm neutral atmospheric fog matching light minimal cream background (#faf8f5)
        scene.fog = new THREE.FogExp2(0xfaf8f5, 0.018);
        const camera = new THREE.PerspectiveCamera(38, width / height, 0.1, 1000);
        camera.position.set(0, 22, 38);
        camera.lookAt(0, 1, 0);
        const renderer = new THREE.WebGLRenderer({
          antialias: true,
          alpha: true,
          powerPreference: 'high-performance'
        });
        renderer.setSize(width, height);
        renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));
        renderer.shadowMap.enabled = true;
        renderer.shadowMap.type = THREE.PCFSoftShadowMap;
        renderer.toneMapping = THREE.ACESFilmicToneMapping;
        renderer.toneMappingExposure = 1.15;
        renderer.domElement.style.width = '100%';
        renderer.domElement.style.height = '100%';
        renderer.domElement.style.display = 'block';
        renderer.domElement.style.touchAction = 'none';
        renderer.domElement.style.cursor = 'grab';
        containerEl.appendChild(renderer.domElement);

        // Lighting System
        const ambientLight = new THREE.AmbientLight(0xffffff, 0.88);
        scene.add(ambientLight);
        const dirLight = new THREE.DirectionalLight(0xfff9f0, 1.35);
        dirLight.position.set(16, 36, 22);
        dirLight.castShadow = true;
        dirLight.shadow.mapSize.width = 2048;
        dirLight.shadow.mapSize.height = 2048;
        dirLight.shadow.camera.near = 0.5;
        dirLight.shadow.camera.far = 120;
        const d = 32;
        dirLight.shadow.camera.left = -d;
        dirLight.shadow.camera.right = d;
        dirLight.shadow.camera.top = d;
        dirLight.shadow.camera.bottom = -d;
        dirLight.shadow.bias = -0.0003;
        scene.add(dirLight);
        const softFill = new THREE.DirectionalLight(0xe5effa, 0.6);
        softFill.position.set(-22, 22, -18);
        scene.add(softFill);
        const warmRim = new THREE.DirectionalLight(0xffeedb, 0.4);
        warmRim.position.set(0, -6, -26);
        scene.add(warmRim);
        const sceneGroup = new THREE.Group();
        scene.add(sceneGroup);
        const toolsAndMatGroup = new THREE.Group();
        sceneGroup.add(toolsAndMatGroup);

        // 1. Procedural High-Res Precision Cutting Mat Texture
        function createMatTexture() {
          const canvas = document.createElement('canvas');
          canvas.width = 2048;
          canvas.height = 1400;
          const ctx = canvas.getContext('2d');

          // Cutting Mat Navy Blue
          ctx.fillStyle = '#1c3d52';
          ctx.fillRect(0, 0, canvas.width, canvas.height);

          // Subtle noise
          ctx.fillStyle = 'rgba(255, 255, 255, 0.02)';
          for (let i = 0; i < 3000; i++) {
            ctx.fillRect(Math.random() * canvas.width, Math.random() * canvas.height, 2, 2);
          }

          // Outer border
          ctx.strokeStyle = 'rgba(255, 255, 255, 0.85)';
          ctx.lineWidth = 4;
          ctx.strokeRect(60, 60, canvas.width - 120, canvas.height - 120);

          // Minor 25px grid
          ctx.lineWidth = 1;
          ctx.strokeStyle = 'rgba(255, 255, 255, 0.16)';
          for (let x = 60; x <= canvas.width - 60; x += 25) {
            ctx.beginPath();
            ctx.moveTo(x, 60);
            ctx.lineTo(x, canvas.height - 60);
            ctx.stroke();
          }
          for (let y = 60; y <= canvas.height - 60; y += 25) {
            ctx.beginPath();
            ctx.moveTo(60, y);
            ctx.lineTo(canvas.width - 60, y);
            ctx.stroke();
          }

          // Major 100px grid
          ctx.lineWidth = 2;
          ctx.strokeStyle = 'rgba(255, 255, 255, 0.42)';
          for (let x = 60; x <= canvas.width - 60; x += 100) {
            ctx.beginPath();
            ctx.moveTo(x, 60);
            ctx.lineTo(x, canvas.height - 60);
            ctx.stroke();
          }
          for (let y = 60; y <= canvas.height - 60; y += 100) {
            ctx.beginPath();
            ctx.moveTo(60, y);
            ctx.lineTo(canvas.width - 60, y);
            ctx.stroke();
          }

          // Numbers
          ctx.font = 'bold 20px monospace';
          ctx.fillStyle = 'rgba(255, 255, 255, 0.85)';
          let cm = 0;
          for (let x = 60; x <= canvas.width - 60; x += 100) {
            ctx.fillText((cm * 10).toString().padStart(2, '0'), x - 12, 45);
            ctx.fillText((cm * 10).toString().padStart(2, '0'), x - 12, canvas.height - 25);
            cm++;
          }

          // Center Branding
          ctx.font = '600 24px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
          ctx.fillStyle = 'rgba(255, 255, 255, 0.4)';
          ctx.textAlign = 'center';
          ctx.fillText('WRAPFIT® PRECISION PACKAGING WORKBENCH • SCALE 1:1 CAD LAB • ECMA/FEFCO COMPLIANT', canvas.width / 2, canvas.height / 2);
          const texture = new THREE.CanvasTexture(canvas);
          texture.anisotropy = 16;
          return texture;
        }

        // Cutting Mat Mesh
        const matTex = createMatTexture();
        const matGeo = new THREE.BoxGeometry(38, 0.3, 26);
        const matMat = new THREE.MeshStandardMaterial({
          map: matTex,
          roughness: 0.45,
          metalness: 0.1
        });
        const matMesh = new THREE.Mesh(matGeo, matMat);
        matMesh.receiveShadow = true;
        matMesh.position.y = 0;
        toolsAndMatGroup.add(matMesh);

        // Soft Table Ground
        const floorMesh = new THREE.Mesh(new THREE.PlaneGeometry(350, 350), new THREE.MeshStandardMaterial({
          color: 0xfaf8f5,
          roughness: 0.92,
          metalness: 0.02
        }));
        floorMesh.rotation.x = -Math.PI / 2;
        floorMesh.position.y = -0.16;
        floorMesh.receiveShadow = true;
        scene.add(floorMesh);

        // Standard Materials
        const chromeMat = new THREE.MeshStandardMaterial({
          color: 0xebedf0,
          metalness: 0.85,
          roughness: 0.22
        });
        const darkRubberMat = new THREE.MeshStandardMaterial({
          color: 0x1f2328,
          roughness: 0.65,
          metalness: 0.15
        });
        const craftPaperMat = new THREE.MeshStandardMaterial({
          color: 0xddcaa8,
          roughness: 0.82,
          metalness: 0.03
        });
        const whiteMatteMat = new THREE.MeshStandardMaterial({
          color: 0xfdfcf9,
          roughness: 0.35,
          metalness: 0.04
        });
        const goldFoilMat = new THREE.MeshStandardMaterial({
          color: 0xebb94d,
          metalness: 0.88,
          roughness: 0.22
        });
        const redEnamelMat = new THREE.MeshStandardMaterial({
          color: 0xb5352c,
          metalness: 0.35,
          roughness: 0.32
        });
        const oliveEnamelMat = new THREE.MeshStandardMaterial({
          color: 0x2e4a3b,
          metalness: 0.35,
          roughness: 0.32
        });
        const yellowTapeMat = new THREE.MeshStandardMaterial({
          color: 0xf6c343,
          roughness: 0.62,
          metalness: 0.08
        });
        const pencilWoodMat = new THREE.MeshStandardMaterial({
          color: 0xe6a838,
          roughness: 0.7,
          metalness: 0.05
        });

        // High contrast materials for CAD Dieline Step 1
        const creaseLineMat = new THREE.MeshBasicMaterial({
          color: 0xd9532f
        }); // High-visibility red dashed score line
        const cutLineMat = new THREE.MeshBasicMaterial({
          color: 0x111111
        }); // Dark clean knife cut line
        const dimLineMat = new THREE.MeshBasicMaterial({
          color: 0x2563eb
        }); // Precision blueprint blue

        // 2. TOOLS ON WORKBENCH
        // Drafting Steel Ruler
        const rulerBlade = new THREE.Mesh(new THREE.BoxGeometry(30, 0.06, 2.2), chromeMat);
        rulerBlade.castShadow = true;
        rulerBlade.receiveShadow = true;
        rulerBlade.position.set(-1, 0.18, -11.2);
        toolsAndMatGroup.add(rulerBlade);

        // Drafting Pencil
        const pencil = new THREE.Group();
        const pBody = new THREE.Mesh(new THREE.CylinderGeometry(0.2, 0.2, 14, 6), pencilWoodMat);
        pBody.rotation.z = Math.PI / 2;
        pBody.castShadow = true;
        const pTip = new THREE.Mesh(new THREE.ConeGeometry(0.2, 0.8, 6), craftPaperMat);
        pTip.rotation.z = -Math.PI / 2;
        pTip.position.x = 7.4;
        const pLead = new THREE.Mesh(new THREE.ConeGeometry(0.08, 0.3, 6), darkRubberMat);
        pLead.rotation.z = -Math.PI / 2;
        pLead.position.x = 7.8;
        const pEraser = new THREE.Mesh(new THREE.CylinderGeometry(0.2, 0.2, 1.2, 16), redEnamelMat);
        pEraser.rotation.z = Math.PI / 2;
        pEraser.position.x = -7.3;
        pencil.add(pBody, pTip, pLead, pEraser);
        pencil.position.set(0, 0.28, -9.6);
        pencil.rotation.y = 0.04;
        toolsAndMatGroup.add(pencil);

        // Precision Scalpel
        const knife = new THREE.Group();
        const handle = new THREE.Mesh(new THREE.BoxGeometry(11, 0.5, 0.8), darkRubberMat);
        handle.castShadow = true;
        const slider = new THREE.Mesh(new THREE.BoxGeometry(1.4, 0.65, 0.5), chromeMat);
        slider.position.set(1.5, 0.1, 0);
        const bladeShape = new THREE.Shape();
        bladeShape.moveTo(0, -0.3);
        bladeShape.lineTo(3.2, -0.3);
        bladeShape.lineTo(1.8, 0.3);
        bladeShape.lineTo(0, 0.3);
        const bladeGeo = new THREE.ExtrudeGeometry(bladeShape, {
          depth: 0.04,
          bevelEnabled: false
        });
        const bladeMesh = new THREE.Mesh(bladeGeo, chromeMat);
        bladeMesh.rotation.x = Math.PI / 2;
        bladeMesh.position.set(5.5, 0.02, 0.15);
        bladeMesh.castShadow = true;
        knife.add(handle, slider, bladeMesh);
        knife.position.set(15.5, 0.35, 4.5);
        knife.rotation.y = -0.52;
        toolsAndMatGroup.add(knife);

        // Scissors
        const scissors = new THREE.Group();
        const blade1 = new THREE.Mesh(new THREE.BoxGeometry(8, 0.08, 0.6), chromeMat);
        blade1.position.x = 2.8;
        blade1.castShadow = true;
        const blade2 = blade1.clone();
        blade2.rotation.y = 0.32;
        const pivotScrew = new THREE.Mesh(new THREE.CylinderGeometry(0.25, 0.25, 0.2, 16), chromeMat);
        pivotScrew.position.set(0, 0.05, 0);
        const loop1 = new THREE.Mesh(new THREE.TorusGeometry(1.2, 0.25, 12, 28), darkRubberMat);
        loop1.position.set(-1.6, 0, 0.8);
        loop1.castShadow = true;
        const loop2 = new THREE.Mesh(new THREE.TorusGeometry(1.2, 0.25, 12, 28), darkRubberMat);
        loop2.position.set(-1.6, 0, -0.8);
        loop2.castShadow = true;
        scissors.add(blade1, blade2, pivotScrew, loop1, loop2);
        scissors.position.set(-15, 0.25, -4.2);
        scissors.rotation.y = 0.75;
        toolsAndMatGroup.add(scissors);

        // Bone Tool & Tape & Cans
        const boneTool = new THREE.Mesh(new THREE.CylinderGeometry(0.35, 0.15, 9.5, 16), whiteMatteMat);
        boneTool.rotation.z = Math.PI / 2.15;
        boneTool.rotation.y = 0.38;
        boneTool.position.set(-13.5, 0.26, 5.2);
        boneTool.castShadow = true;
        toolsAndMatGroup.add(boneTool);
        const tapeRoll = new THREE.Mesh(new THREE.CylinderGeometry(1.8, 1.8, 1.3, 32, 1, true), yellowTapeMat);
        tapeRoll.position.set(-9, 0.7, -7.5);
        tapeRoll.castShadow = true;
        const tapeCore = new THREE.Mesh(new THREE.CylinderGeometry(1.2, 1.2, 1.32, 32), craftPaperMat);
        tapeCore.position.copy(tapeRoll.position);
        toolsAndMatGroup.add(tapeRoll, tapeCore);
        const paintCan1 = new THREE.Mesh(new THREE.CylinderGeometry(1.25, 1.25, 2.4, 24), redEnamelMat);
        paintCan1.position.set(11.5, 1.2, -8.2);
        paintCan1.castShadow = true;
        const paintCan2 = new THREE.Mesh(new THREE.CylinderGeometry(1.35, 1.35, 2.8, 24), oliveEnamelMat);
        paintCan2.position.set(14.5, 1.4, -7.5);
        paintCan2.castShadow = true;
        toolsAndMatGroup.add(paintCan1, paintCan2);

        // 3. PACKAGING STAGES
        const stagesGroup = new THREE.Group();
        stagesGroup.position.set(0, 0.2, 0.5);
        sceneGroup.add(stagesGroup);

        // ================= STAGE 1: High Clarity Dieline CAD Runner =================
        const stage1 = new THREE.Group();

        // Model Kit Runner Frame
        const sprueMat = new THREE.MeshStandardMaterial({
          color: 0xf5f3ed,
          roughness: 0.4,
          metalness: 0.1
        });
        const sprueR1 = new THREE.Mesh(new THREE.BoxGeometry(20, 0.22, 0.28), sprueMat);
        sprueR1.position.z = -7.5;
        const sprueR2 = new THREE.Mesh(new THREE.BoxGeometry(20, 0.22, 0.28), sprueMat);
        sprueR2.position.z = 7.5;
        const sprueC1 = new THREE.Mesh(new THREE.BoxGeometry(0.28, 0.22, 15), sprueMat);
        sprueC1.position.x = -10;
        const sprueC2 = new THREE.Mesh(new THREE.BoxGeometry(0.28, 0.22, 15), sprueMat);
        sprueC2.position.x = 10;
        stage1.add(sprueR1, sprueR2, sprueC1, sprueC2);

        // Kraft Dieline Blank
        const baseFlap = new THREE.Mesh(new THREE.BoxGeometry(5.2, 0.08, 5.2), craftPaperMat);
        baseFlap.castShadow = true;
        baseFlap.receiveShadow = true;
        const flapTop = new THREE.Mesh(new THREE.BoxGeometry(5.2, 0.07, 3.6), craftPaperMat);
        flapTop.position.set(0, 0, -4.4);
        const flapBottom = new THREE.Mesh(new THREE.BoxGeometry(5.2, 0.07, 3.6), craftPaperMat);
        flapBottom.position.set(0, 0, 4.4);
        const flapRight = new THREE.Mesh(new THREE.BoxGeometry(3.6, 0.07, 5.2), craftPaperMat);
        flapRight.position.set(4.4, 0, 0);
        const flapLeft = new THREE.Mesh(new THREE.BoxGeometry(3.6, 0.07, 5.2), craftPaperMat);
        flapLeft.position.set(-4.4, 0, 0);
        stage1.add(baseFlap, flapTop, flapBottom, flapRight, flapLeft);

        // CLEAR CREASE & CUT CAD LINES (Làm rõ các nếp gấp & đường cấn dao)
        function createDottedCreaseLine(x, z, length, isHorizontal) {
          const group = new THREE.Group();
          const segments = 12;
          const segLen = length / segments * 0.55;
          for (let i = 0; i < segments; i++) {
            const offset = -length / 2 + (i + 0.5) * (length / segments);
            const dash = new THREE.Mesh(isHorizontal ? new THREE.BoxGeometry(segLen, 0.04, 0.08) : new THREE.BoxGeometry(0.08, 0.04, segLen), creaseLineMat);
            if (isHorizontal) dash.position.set(x + offset, 0.05, z);else dash.position.set(x, 0.05, z + offset);
            group.add(dash);
          }
          return group;
        }

        // 4 Primary Score/Fold Lines (Nếp gấp cấn gân đỏ kỹ thuật)
        stage1.add(createDottedCreaseLine(0, -2.6, 5.2, true));
        stage1.add(createDottedCreaseLine(0, 2.6, 5.2, true));
        stage1.add(createDottedCreaseLine(-2.6, 0, 5.2, false));
        stage1.add(createDottedCreaseLine(2.6, 0, 5.2, false));

        // Knife Cut Outer Perimeter (Đường dao bế sắc nét)
        const cutPerimeter = new THREE.Group();
        function addCutLine(x1, z1, x2, z2) {
          const dx = x2 - x1;
          const dz = z2 - z1;
          const len = Math.sqrt(dx * dx + dz * dz);
          const line = new THREE.Mesh(new THREE.BoxGeometry(len, 0.02, 0.06), cutLineMat);
          line.position.set((x1 + x2) / 2, 0.045, (z1 + z2) / 2);
          line.rotation.y = -Math.atan2(dz, dx);
          cutPerimeter.add(line);
        }
        // Flap contours
        addCutLine(-2.6, -6.2, 2.6, -6.2);
        addCutLine(-2.6, -2.6, -2.6, -6.2);
        addCutLine(2.6, -2.6, 2.6, -6.2);
        addCutLine(-2.6, 6.2, 2.6, 6.2);
        addCutLine(-2.6, 2.6, -2.6, 6.2);
        addCutLine(2.6, 2.6, 2.6, 6.2);
        addCutLine(-6.2, -2.6, -6.2, 2.6);
        addCutLine(-2.6, -2.6, -6.2, -2.6);
        addCutLine(-2.6, 2.6, -6.2, 2.6);
        addCutLine(6.2, -2.6, 6.2, 2.6);
        addCutLine(2.6, -2.6, 6.2, -2.6);
        addCutLine(2.6, 2.6, 6.2, 2.6);
        stage1.add(cutPerimeter);

        // Gates connecting to sprue
        const gate1 = new THREE.Mesh(new THREE.BoxGeometry(0.3, 0.08, 1.4), sprueMat);
        gate1.position.set(0, 0, -6.8);
        const gate2 = new THREE.Mesh(new THREE.BoxGeometry(0.3, 0.08, 1.4), sprueMat);
        gate2.position.set(0, 0, 6.8);
        const gate3 = new THREE.Mesh(new THREE.BoxGeometry(1.4, 0.08, 0.3), sprueMat);
        gate3.position.set(-7.0, 0, 0);
        const gate4 = new THREE.Mesh(new THREE.BoxGeometry(1.4, 0.08, 0.3), sprueMat);
        gate4.position.set(7.0, 0, 0);
        stage1.add(gate1, gate2, gate3, gate4);
        stagesGroup.add(stage1);

        // ================= STAGE 2: Interactive Dynamic Folding Box =================
        const stage2 = new THREE.Group();
        const foldFloor = new THREE.Mesh(new THREE.BoxGeometry(5.8, 0.12, 5.8), craftPaperMat);
        foldFloor.castShadow = true;
        foldFloor.receiveShadow = true;
        stage2.add(foldFloor);

        // Hinges
        const hingeN = new THREE.Group();
        hingeN.position.set(0, 0.06, -2.9);
        const wallN = new THREE.Mesh(new THREE.BoxGeometry(5.8, 0.1, 4.4), craftPaperMat);
        wallN.position.set(0, 0, -2.2);
        wallN.castShadow = true;
        hingeN.add(wallN);
        const hingeS = new THREE.Group();
        hingeS.position.set(0, 0.06, 2.9);
        const wallS = new THREE.Mesh(new THREE.BoxGeometry(5.8, 0.1, 4.4), craftPaperMat);
        wallS.position.set(0, 0, 2.2);
        wallS.castShadow = true;
        hingeS.add(wallS);
        const hingeE = new THREE.Group();
        hingeE.position.set(2.9, 0.06, 0);
        const wallE = new THREE.Mesh(new THREE.BoxGeometry(4.4, 0.1, 5.8), craftPaperMat);
        wallE.position.set(2.2, 0, 0);
        wallE.castShadow = true;
        hingeE.add(wallE);
        const hingeW = new THREE.Group();
        hingeW.position.set(-2.9, 0.06, 0);
        const wallW = new THREE.Mesh(new THREE.BoxGeometry(4.4, 0.1, 5.8), craftPaperMat);
        wallW.position.set(-2.2, 0, 0);
        wallW.castShadow = true;
        hingeW.add(wallW);
        stage2.add(hingeN, hingeS, hingeE, hingeW);
        stagesGroup.add(stage2);

        // ================= STAGE 3: Luxury Assembled Finished Packaging =================
        const stage3 = new THREE.Group();

        // Pedestal / Floating Shadow Base for Stage 3 Focus
        const pedestal = new THREE.Mesh(new THREE.CylinderGeometry(8.5, 9.2, 0.6, 64), new THREE.MeshStandardMaterial({
          color: 0xf3efe6,
          roughness: 0.45,
          metalness: 0.08
        }));
        pedestal.position.y = 0.3;
        pedestal.receiveShadow = true;
        const boxBase = new THREE.Mesh(new THREE.BoxGeometry(6.6, 5.2, 6.6), whiteMatteMat);
        boxBase.position.y = 3.2;
        boxBase.castShadow = true;
        boxBase.receiveShadow = true;
        const goldCollar = new THREE.Mesh(new THREE.BoxGeometry(6.3, 0.7, 6.3), goldFoilMat);
        goldCollar.position.y = 5.85;
        goldCollar.castShadow = true;
        const lidGroup = new THREE.Group();
        lidGroup.position.set(1.2, 7.3, 0.8);
        lidGroup.rotation.set(-0.25, 0.2, 0.32);
        const lidMesh = new THREE.Mesh(new THREE.BoxGeometry(7.0, 1.5, 7.0), whiteMatteMat);
        lidMesh.castShadow = true;
        const logoSeal = new THREE.Mesh(new THREE.CylinderGeometry(1.2, 1.2, 0.08, 32), goldFoilMat);
        logoSeal.position.set(0, 0.78, 0);
        logoSeal.castShadow = true;
        lidGroup.add(lidMesh, logoSeal);
        stage3.add(pedestal, boxBase, goldCollar, lidGroup);
        stagesGroup.add(stage3);

        // 4. SMOOTH INTERPOLATION & STEP STATE MACHINE
        let currentStep = 1;
        let targetStep = 1;
        let transitionProgress = 1.0; // 0 to 1 during transition

        // Animation targets
        let targetToolsOpacity = 1.0;
        let currentToolsOpacity = 1.0;
        let targetStage1Scale = 1.0;
        let targetStage2Scale = 0.001;
        let targetStage3Scale = 0.001;
        let currentStage1Scale = 1.0;
        let currentStage2Scale = 0.001;
        let currentStage3Scale = 0.001;
        let foldAngleTarget = 0;
        let foldAngleCurrent = 0;

        // Camera & Orbit targets
        let isDragging = false;
        let prevMouse = {
          x: 0,
          y: 0
        };
        let targetRotY = 0.35;
        let currentRotY = 0.35;
        let targetRotX = 0.02;
        let currentRotX = 0.02;
        let targetCamY = 22;
        let currentCamY = 22;
        let targetCamZ = 38;
        let currentCamZ = 38;
        window.setWorkbenchStep = function (stepNum) {
          targetStep = stepNum;
          currentStep = stepNum;
          if (stepNum === 1) {
            // Step 1: CAD Dieline Kit
            targetToolsOpacity = 1.0;
            targetStage1Scale = 1.0;
            targetStage2Scale = 0.001;
            targetStage3Scale = 0.001;
            foldAngleTarget = 0;
            targetRotY = 0.15;
            targetRotX = 0.02;
            targetCamY = 24;
            targetCamZ = 38;
          } else if (stepNum === 2) {
            // Step 2: Dynamic Origami Folding
            targetToolsOpacity = 0.85;
            targetStage1Scale = 0.001;
            targetStage2Scale = 1.0;
            targetStage3Scale = 0.001;
            foldAngleTarget = Math.PI / 2.2;
            targetRotY = 0.75;
            targetRotX = 0.08;
            targetCamY = 20;
            targetCamZ = 32;
          } else if (stepNum === 3) {
            // Step 3: Finished Product - Lọc bỏ bảng & bộ công cụ, tập trung hoàn toàn vào sản phẩm
            targetToolsOpacity = 0.0;
            targetStage1Scale = 0.001;
            targetStage2Scale = 0.001;
            targetStage3Scale = 1.0;
            targetRotY = 2.45;
            targetRotX = -0.04;
            targetCamY = 15;
            targetCamZ = 26;
          }
        };

        // Backwards compatibility hook
        window.setWorkbenchCameraView = function (viewType) {
          if (viewType === 'kit') window.setWorkbenchStep(1);else if (viewType === 'fold') window.setWorkbenchStep(2);else if (viewType === 'studio') window.setWorkbenchStep(3);
        };
        window.setWorkbenchStage = function (stageNum) {
          window.setWorkbenchStep(stageNum);
        };

        // 360 Drag Orbit
        function onPointerDown(e) {
          isDragging = true;
          prevMouse = {
            x: e.clientX,
            y: e.clientY
          };
          renderer.domElement.style.cursor = 'grabbing';
        }
        function onPointerMove(e) {
          if (isDragging) {
            const dx = e.clientX - prevMouse.x;
            const dy = e.clientY - prevMouse.y;
            targetRotY += dx * 0.006;
            targetRotX = Math.max(-0.25, Math.min(0.28, targetRotX + dy * 0.004));
            prevMouse = {
              x: e.clientX,
              y: e.clientY
            };
          }
        }
        function onPointerUp() {
          isDragging = false;
          renderer.domElement.style.cursor = 'grab';
        }
        renderer.domElement.addEventListener('pointerdown', onPointerDown);
        window.addEventListener('pointermove', onPointerMove);
        window.addEventListener('pointerup', onPointerUp);
        function onResize() {
          const w = containerEl.clientWidth || window.innerWidth || 1440;
          const h = containerEl.clientHeight || window.innerHeight || 900;
          camera.aspect = w / h;
          camera.updateProjectionMatrix();
          renderer.setSize(w, h);
        }
        window.addEventListener('resize', onResize);

        // Initial State: Step 1
        window.setWorkbenchStep(1);

        // Render Loop with smooth continuous interpolation
        const clock = new THREE.Clock();
        function animate() {
          requestAnimationFrame(animate);
          const elapsed = clock.getElapsedTime();
          if (!isDragging) {
            targetRotY += 0.0012; // slow ambient drift
          }

          // Smooth Orbit & Camera lerp
          currentRotY += (targetRotY - currentRotY) * 0.06;
          currentRotX += (targetRotX - currentRotX) * 0.06;
          currentCamY += (targetCamY - currentCamY) * 0.05;
          currentCamZ += (targetCamZ - currentCamZ) * 0.05;
          camera.position.y = currentCamY;
          camera.position.z = currentCamZ;

          // Look slightly higher when focusing on finished product in Step 3
          const lookTargetY = targetStep === 3 ? 2.8 : 1.2;
          camera.lookAt(0, lookTargetY, 0);
          sceneGroup.rotation.y = currentRotY;
          sceneGroup.rotation.x = currentRotX;

          // Smooth Step Scaling Transitions
          currentStage1Scale += (targetStage1Scale - currentStage1Scale) * 0.08;
          currentStage2Scale += (targetStage2Scale - currentStage2Scale) * 0.08;
          currentStage3Scale += (targetStage3Scale - currentStage3Scale) * 0.08;
          stage1.scale.set(currentStage1Scale, currentStage1Scale, currentStage1Scale);
          stage2.scale.set(currentStage2Scale, currentStage2Scale, currentStage2Scale);
          stage3.scale.set(currentStage3Scale, currentStage3Scale, currentStage3Scale);
          stage1.visible = currentStage1Scale > 0.01;
          stage2.visible = currentStage2Scale > 0.01;
          stage3.visible = currentStage3Scale > 0.01;

          // Tools & Mat Visibility / Hide in Step 3
          currentToolsOpacity += (targetToolsOpacity - currentToolsOpacity) * 0.07;
          toolsAndMatGroup.scale.set(Math.max(0.001, currentToolsOpacity), Math.max(0.001, currentToolsOpacity), Math.max(0.001, currentToolsOpacity));
          toolsAndMatGroup.visible = currentToolsOpacity > 0.01;

          // Dynamic Folding Animation in Step 2
          if (stage2.visible) {
            foldAngleCurrent += (foldAngleTarget - foldAngleCurrent) * 0.06;
            const foldWave = Math.sin(elapsed * 2.4) * 0.08;
            const effectiveAngle = foldAngleCurrent + foldWave;
            hingeN.rotation.x = effectiveAngle;
            hingeS.rotation.x = -effectiveAngle;
            hingeE.rotation.z = -effectiveAngle;
            hingeW.rotation.z = effectiveAngle;
          }

          // Floating Lid Float in Step 3
          if (stage3.visible) {
            lidGroup.position.y = 7.3 + Math.sin(elapsed * 2.0) * 0.15;
            lidGroup.rotation.z = 0.32 + Math.cos(elapsed * 1.6) * 0.02;
          }
          renderer.render(scene, camera);
        }
        animate();
      })();
    })();
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  try {
    document.addEventListener('DOMContentLoaded', () => {
      let activeIndex = 1;
      const stageButtons = document.querySelectorAll('.stage-button');
      const launchBtn = document.getElementById('btn-launch-studio');

      // Subtle audio feedback synthesize
      function playFeedbackClick() {
        try {
          const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
          const osc = audioCtx.createOscillator();
          const gain = audioCtx.createGain();
          osc.type = 'sine';
          osc.frequency.setValueAtTime(800, audioCtx.currentTime);
          osc.frequency.exponentialRampToValueAtTime(400, audioCtx.currentTime + 0.04);
          gain.gain.setValueAtTime(0.04, audioCtx.currentTime);
          gain.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + 0.04);
          osc.connect(gain);
          gain.connect(audioCtx.destination);
          osc.start();
          osc.stop(audioCtx.currentTime + 0.04);
        } catch (e) {}
      }
      function updateButtonStates(targetIndex) {
        activeIndex = targetIndex;
        stageButtons.forEach(btn => {
          const stage = parseInt(btn.getAttribute('data-stage'), 10);
          const dot = btn.querySelector('span:first-child');
          if (stage === activeIndex) {
            btn.className = 'stage-button active flex items-center gap-2 px-4 py-2 rounded-full text-xs font-mono-tech transition-all duration-200 bg-[#121517] text-white shadow-sm';
            if (dot) {
              dot.className = 'w-1.5 h-1.5 rounded-full bg-white opacity-90';
            }
          } else {
            btn.className = 'stage-button flex items-center gap-2 px-4 py-2 rounded-full text-xs font-mono-tech transition-all duration-200 text-neutral-700 hover:text-black hover:bg-black/5';
            if (dot) {
              dot.className = 'w-1.5 h-1.5 rounded-full bg-neutral-400';
            }
          }
        });
      }
      function switchStage(stageNum, viewType) {
        playFeedbackClick();
        if (typeof window.setWorkbenchStep === 'function') {
          window.setWorkbenchStep(stageNum);
        } else if (typeof window.setWorkbenchCameraView === 'function' && viewType) {
          window.setWorkbenchCameraView(viewType);
        } else if (typeof window.setWorkbenchStage === 'function') {
          window.setWorkbenchStage(stageNum);
        }
        updateButtonStates(stageNum);
      }
      stageButtons.forEach(btn => {
        btn.addEventListener('click', () => {
          const stage = parseInt(btn.getAttribute('data-stage'), 10);
          const view = btn.getAttribute('data-view');
          switchStage(stage, view);
        });
      });

      // Keyboard numerical shortcuts (1, 2, 3)
      window.addEventListener('keydown', e => {
        if (e.key === '1') switchStage(1, 'kit');else if (e.key === '2') switchStage(2, 'fold');else if (e.key === '3') switchStage(3, 'studio');
      });

      // Launch Experience trigger transitions smoothly to Stage 3 / Studio
      if (launchBtn) {
        launchBtn.addEventListener('click', e => {
          e.preventDefault();
          switchStage(3, 'studio');
          launchBtn.classList.add('scale-95');
          setTimeout(() => {
            launchBtn.classList.remove('scale-95');
          }, 200);
        });
      }
    });
  } catch (error) {
    console.error('[stitch] script 2 failed', error);
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        window.setWorkbenchStep ? window.setWorkbenchStep(1) : window.setWorkbenchCameraView && window.setWorkbenchCameraView('kit');
      },
      /* click */ "1": function (event) {
        window.setWorkbenchStep ? window.setWorkbenchStep(2) : window.setWorkbenchCameraView && window.setWorkbenchCameraView('fold');
      },
      /* click */ "2": function (event) {
        window.setWorkbenchStep ? window.setWorkbenchStep(3) : window.setWorkbenchCameraView && window.setWorkbenchCameraView('studio');
      },
    },
  };
});
