// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/2f24a2213dd74cd788a227223a8190c9.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  // Classic scripts publish top-level functions on window.
  window.showToast = showToast;
  window.restoreProject = restoreProject;
  window.openAssistantDialog = openAssistantDialog;

  function showToast(message) {
    const toast = document.getElementById('status-toast');
    const toastText = document.getElementById('toast-message');
    if (!toast || !toastText) return;
    toastText.textContent = message;
    toast.classList.remove('opacity-0', 'translate-y-3', 'pointer-events-none');
    toast.classList.add('opacity-100', 'translate-y-0');
    setTimeout(() => {
      toast.classList.remove('opacity-100', 'translate-y-0');
      toast.classList.add('opacity-0', 'translate-y-3', 'pointer-events-none');
    }, 3200);
  }
  function restoreProject(btn) {
    const originalHTML = btn.innerHTML;
    btn.innerHTML = `<span class="material-symbols-outlined animate-spin text-[18px]">progress_activity</span><span>Đang phục hồi CAD...</span>`;
    btn.disabled = true;
    setTimeout(() => {
      btn.innerHTML = `<span class="material-symbols-outlined text-[18px]">verified</span><span>Đã Khôi Phục Thành Công!</span>`;
      btn.classList.remove('bg-[#133020]');
      btn.classList.add('bg-secondary');
      showToast('Bản vẽ bế hộp #WF-9041 đã đồng bộ về 3D Canvas!');
    }, 1100);
  }
  function openAssistantDialog() {
    showToast('Bé Gói: "Tớ đang kiểm tra lịch sử lưu tự động trên Cloud Vault cho bạn..."');
  }
  try {
    document.addEventListener('keydown', e => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault();
        const input = document.getElementById('quick-search-input');
        if (input) input.focus();
      }
    });
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        openAssistantDialog();
      },
      /* click */ "1": function (event) {
        restoreProject(this);
      },
    },
  };
});
