// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/ba6c0fce8eb847a8a45264725b4b998c.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  // Classic scripts publish top-level functions on window.
  window.expandCategory = expandCategory;
  window.resetToGrid = resetToGrid;
  window.markCurrentAsRead = markCurrentAsRead;

  let categories;
  let activeCat;
  function expandCategory(catKey) {
    activeCat = catKey;
    const data = categories[catKey];
    if (!data) return;
    const gridCards = document.getElementById("grid-cards");
    const expandedView = document.getElementById("expanded-view");
    const btnReset = document.getElementById("btn-reset-view");
    const badge = document.getElementById("current-view-badge");

    // Smooth switch
    gridCards.classList.add("hidden");
    expandedView.classList.remove("hidden");
    setTimeout(() => {
      expandedView.classList.remove("opacity-0");
    }, 20);
    btnReset.classList.remove("hidden");
    badge.textContent = data.name;

    // Update hero card attributes
    const hero = document.getElementById("expanded-card-hero");
    hero.className = `relative folded-corner rounded-3xl p-6 md:p-8 text-stone-950 custom-bezier shadow-md flex flex-col justify-between ${data.bgColor}`;
    document.getElementById("hero-count").textContent = data.count;
    document.getElementById("hero-title").textContent = data.name;
    document.getElementById("hero-desc").textContent = data.desc;
    document.getElementById("hero-stat-badge").textContent = data.statBadge;
    document.getElementById("hero-tag").textContent = data.tag;

    // Highlight dock button
    document.querySelectorAll(".dock-btn").forEach(btn => {
      btn.classList.add("opacity-60", "scale-95");
      btn.classList.remove("ring-2", "ring-black", "opacity-100", "scale-100");
    });
    const activeDock = document.getElementById(`dock-${catKey}`);
    if (activeDock) {
      activeDock.classList.remove("opacity-60", "scale-95");
      activeDock.classList.add("ring-2", "ring-stone-900", "opacity-100", "scale-100");
    }

    // Populate list
    const listContainer = document.getElementById("notification-list");
    listContainer.innerHTML = data.items.map(item => `
          <div class="p-4 rounded-2xl bg-surface-container-low hover:bg-surface-container border border-surface-container-high transition-all flex flex-col gap-2">
            <div class="flex items-center justify-between gap-2">
              <div class="flex items-center gap-2">
                <span class="px-2.5 py-0.5 rounded-full bg-surface-container-highest text-on-surface font-cad-spec-micro text-[11px] font-bold uppercase tracking-wider">
                  ${item.badge}
                </span>
                <span class="font-cad-dimension text-xs font-semibold text-primary">
                  ${item.sub}
                </span>
              </div>
              <span class="font-cad-spec-micro text-xs text-outline">${item.time}</span>
            </div>
            <h4 class="font-headline-sm text-base font-bold text-on-surface">${item.title}</h4>
            <p class="font-body-md text-xs md:text-sm text-on-surface-variant leading-relaxed">${item.desc}</p>
            ${item.actions && item.actions.length ? `
              <div class="mt-2 flex flex-wrap items-center gap-2 pt-1 border-t border-surface-container-high/60">
                ${item.actions.map(act => `
                  <button class="px-3 py-1.5 rounded-xl font-label-ui text-xs font-semibold inline-flex items-center gap-1.5 transition-all ${act.primary ? 'bg-primary-container text-white hover:bg-primary shadow-sm' : 'bg-surface-container-highest hover:bg-surface-container-high text-on-surface'}">
                    <span class="material-symbols-outlined text-[15px]">${act.icon}</span>
                    <span>${act.label}</span>
                  </button>
                `).join('')}
              </div>
            ` : ''}
          </div>
        `).join('');
  }
  function resetToGrid() {
    activeCat = null;
    const gridCards = document.getElementById("grid-cards");
    const expandedView = document.getElementById("expanded-view");
    const btnReset = document.getElementById("btn-reset-view");
    const badge = document.getElementById("current-view-badge");
    expandedView.classList.add("opacity-0");
    setTimeout(() => {
      expandedView.classList.add("hidden");
      gridCards.classList.remove("hidden");
    }, 200);
    btnReset.classList.add("hidden");
    badge.textContent = "Tất cả phân loại (Lưới 2x2)";
  }
  function markCurrentAsRead() {
    const btn = document.getElementById("btn-mark-active");
    if (btn) {
      btn.innerHTML = `<span class="material-symbols-outlined text-[15px] text-emerald-600">check_circle</span><span class="text-emerald-700">Đã cập nhật tất cả</span>`;
    }
  }
  try {
    (categories = {
      fitcheck: {
        name: "FitCheck™ Kỹ Thuật",
        count: "3+",
        statBadge: "3 CẢNH BÁO",
        bgColor: "bg-accent-orange",
        desc: "Sai số nếp gấp, nắp gài RTE Box và bù trừ caliper K-Factor.",
        tag: "Δ 0.08mm K-Factor OK",
        items: [{
          title: "Hiệu chỉnh độ giãn nở nắp gài RTE Box hoàn tất",
          sub: "Δ 0.08 mm",
          badge: "FitCheck™ Calibrated",
          time: "10:42 AM",
          desc: "Caliper 0.42mm bù trừ +0.08mm K-factor thành công cho giấy Bristol 350gsm. Dung sai dao bế đã cân bằng chuẩn khuôn dập.",
          actions: [{
            label: "Xem chi tiết CAD",
            icon: "visibility",
            primary: true
          }, {
            label: "Tải Dieline DXF",
            icon: "file_download",
            primary: false
          }]
        }, {
          title: "Cảnh báo nếp cấn mép bôi keo dập tự động Bobst 106",
          sub: "3.0mm khoảng lùi",
          badge: "Tối ưu dao cắt",
          time: "Hôm qua",
          desc: "Đã tự động thụt mép keo 3.0mm để hạn chế hiện tượng tràn keo khi vận hành ở tốc độ cao 8,500 tờ/giờ.",
          actions: [{
            label: "Xác nhận quy chuẩn",
            icon: "check",
            primary: false
          }]
        }, {
          title: "Dung sai bù gân sóng E đạt tiêu chuẩn ISO 12647",
          sub: "1.4mm chiều cao",
          badge: "Sóng Carton E",
          time: "2 ngày trước",
          desc: "Đã cân đối lực dập dao gân giữa 2 lớp sóng mộc, triệt tiêu hoàn toàn hiện tượng nứt gãy giấy lót mặt ngoài.",
          actions: [{
            label: "Kiểm tra biểu đồ lực",
            icon: "show_chart",
            primary: false
          }]
        }]
      },
      render: {
        name: "Render 3D & Mockup",
        count: "2+",
        statBadge: "2 HOÀN TẤT",
        bgColor: "bg-accent-yellow",
        desc: "Tiến trình Raytracing 4K, bản xuất UV dập nổi ép kim 24K.",
        tag: "Raytrace 4K • 60 FPS",
        items: [{
          title: "Hoàn tất render PBR Raytracing 4K nắp hộp nam châm ép kim 24K",
          sub: "3840 × 2160 px",
          badge: "Render 4K Ready",
          time: "09:15 AM",
          desc: "Phiên bản phủ UV định hình cát vàng 24K và hiệu ứng dập nổi Blind Emboss 1.2mm đã dựng xong với độ phân giải siêu nét.",
          actions: [{
            label: "Tải trọn bộ 4K (ZIP 48MB)",
            icon: "download",
            primary: true
          }, {
            label: "Xem tương tác 360°",
            icon: "open_in_new",
            primary: false
          }]
        }, {
          title: "Mô phỏng gập mở 360° nắp gài đôi hoàn tất",
          sub: "WebGL Canvas",
          badge: "Mô phỏng động học",
          time: "Hôm qua",
          desc: "Tỷ lệ kháng uốn 180° khớp hoàn toàn với độ đàn hồi giấy Ivory 300gsm thực tế.",
          actions: [{
            label: "Mở Canvas 3D",
            icon: "play_circle",
            primary: false
          }]
        }]
      },
      collab: {
        name: "Cộng Tác & Team",
        count: "5+",
        statBadge: "5 CẬP NHẬT",
        bgColor: "bg-accent-blue",
        desc: "Phê duyệt ma trận vật liệu từ nhãn hàng và đối tác xưởng.",
        tag: "Cloud Vault SHA-256",
        items: [{
          title: "Art Director đã phê duyệt mẫu vân giấy Kraft Mộc v3.2",
          sub: "Đã ký duyệt",
          badge: "Client Sign-off",
          time: "11:30 AM",
          desc: "Đã xác nhận phối màu mực in gốc đậu nành CMYK trên bề mặt kraft tái chế thân thiện môi trường.",
          actions: [{
            label: "Xem lịch sử bản vẽ",
            icon: "history",
            primary: false
          }, {
            label: "Chia sẻ liên kết",
            icon: "share",
            primary: false
          }]
        }, {
          title: "Bé Gói AI Copilot đã cập nhật ghi chú đóng gói cho xưởng in",
          sub: "AI Suggested",
          badge: "WrapFit Copilot",
          time: "Hôm qua",
          desc: "Tối ưu hóa sắp đặt khổ in 4-up trên tấm bìa 720x1020mm, tiết kiệm 8.4% hao hụt giấy lề phôi.",
          actions: [{
            label: "Áp dụng gợi ý",
            icon: "auto_fix_high",
            primary: true
          }]
        }]
      },
      print: {
        name: "Chế Bản & Xưởng In",
        count: "100%",
        statBadge: "100% KHỚP",
        bgColor: "bg-accent-green",
        desc: "Bàn giao lệnh in CNC Zünd, Bobst 106 và file vector FOGRA39.",
        tag: "Zünd G3 & Bobst 106",
        items: [{
          title: "Xuất lệnh cắt CNC Zünd file DXF tỉ lệ 1:1 thành công",
          sub: "Zünd G3 Ready",
          badge: "CNC Lệnh Cắt",
          time: "08:20 AM",
          desc: "Đã gán mã dao: Bút vẽ nếp cấn R1 và dao cắt rung đa năng EOT-250 chuẩn xác milimet.",
          actions: [{
            label: "Tải lệnh máy CNC (.nc)",
            icon: "download",
            primary: true
          }, {
            label: "Xem sơ đồ gá đặt",
            icon: "map",
            primary: false
          }]
        }, {
          title: "Khớp hồ sơ dao bế Bobst 106 với xưởng Bao Bì Đông Á",
          sub: "8,500 tờ/giờ",
          badge: "Offset Approved",
          time: "3 ngày trước",
          desc: "Hồ sơ kỹ thuật đã được kỹ sư trưởng xưởng in tiếp nhận và xác thực thông số ép vát.",
          actions: [{
            label: "In phiếu bàn giao",
            icon: "print",
            primary: false
          }]
        }]
      }
    });
    (activeCat = null);
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        resetToGrid();
      },
      /* click */ "1": function (event) {
        expandCategory('fitcheck');
      },
      /* click */ "2": function (event) {
        expandCategory('render');
      },
      /* click */ "3": function (event) {
        expandCategory('collab');
      },
      /* click */ "4": function (event) {
        expandCategory('print');
      },
      /* click */ "5": function (event) {
        expandCategory('fitcheck');
      },
      /* click */ "6": function (event) {
        expandCategory('render');
      },
      /* click */ "7": function (event) {
        expandCategory('collab');
      },
      /* click */ "8": function (event) {
        expandCategory('print');
      },
      /* click */ "9": function (event) {
        resetToGrid();
      },
      /* click */ "10": function (event) {
        markCurrentAsRead();
      },
    },
  };
});
