// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/c07e6191b5894077a0e34fc5088a141e.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  try {
    (function () {
      const annualBtn = document.getElementById('billing-annual');
      const monthlyBtn = document.getElementById('billing-monthly');
      const priceElements = document.querySelectorAll('.price-display');
      const subtext = document.querySelector('.billing-subtext');
      let isAnnual = true;
      let isUSD = true;
      const usdToVndRate = 25400;
      function formatPrice(usdVal) {
        if (!isUSD) {
          const num = parseInt(usdVal.replace('$', ''), 10);
          return (num * usdToVndRate).toLocaleString('vi-VN') + ' ₫';
        }
        return usdVal;
      }
      function updatePrices() {
        priceElements.forEach(el => {
          const rawVal = isAnnual ? el.getAttribute('data-annual') : el.getAttribute('data-monthly');
          el.textContent = formatPrice(rawVal);
        });
        if (subtext) {
          if (isAnnual) {
            subtext.style.display = 'inline-block';
            subtext.textContent = isUSD ? 'tiết kiệm $60/năm' : 'tiết kiệm 1.500.000 ₫/năm';
          } else {
            subtext.style.display = 'none';
          }
        }
      }
      annualBtn?.addEventListener('click', () => {
        if (isAnnual) return;
        isAnnual = true;
        annualBtn.className = 'px-5 py-1.5 rounded-full font-label-ui text-label-ui bg-surface-container-lowest text-on-surface shadow-sm transition-all duration-200 flex items-center gap-1.5';
        monthlyBtn.className = 'px-5 py-1.5 rounded-full font-label-ui text-label-ui text-on-surface-variant hover:text-on-surface transition-all duration-200';
        updatePrices();
      });
      monthlyBtn?.addEventListener('click', () => {
        if (!isAnnual) return;
        isAnnual = false;
        monthlyBtn.className = 'px-5 py-1.5 rounded-full font-label-ui text-label-ui bg-surface-container-lowest text-on-surface shadow-sm transition-all duration-200 flex items-center gap-1.5';
        annualBtn.className = 'px-5 py-1.5 rounded-full font-label-ui text-label-ui text-on-surface-variant hover:text-on-surface transition-all duration-200 flex items-center gap-1.5';
        updatePrices();
      });
      const currUsdBtn = document.getElementById('curr-usd');
      const currVndBtn = document.getElementById('curr-vnd');
      currUsdBtn?.addEventListener('click', () => {
        if (isUSD) return;
        isUSD = true;
        currUsdBtn.className = 'px-2 py-0.5 rounded-full font-cad-dimension text-cad-dimension bg-surface-container text-on-surface font-semibold transition-all';
        currVndBtn.className = 'px-2 py-0.5 rounded-full font-cad-dimension text-cad-dimension text-on-surface-variant hover:text-on-surface transition-all';
        updatePrices();
      });
      currVndBtn?.addEventListener('click', () => {
        if (!isUSD) return;
        isUSD = false;
        currVndBtn.className = 'px-2 py-0.5 rounded-full font-cad-dimension text-cad-dimension bg-surface-container text-on-surface font-semibold transition-all';
        currUsdBtn.className = 'px-2 py-0.5 rounded-full font-cad-dimension text-cad-dimension text-on-surface-variant hover:text-on-surface transition-all';
        updatePrices();
      });
    })();
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
    },
  };
});
