/* AUTO-GENERATED by `npm run stitch:sync` from stitch/screens.json. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { StitchBehavior } from '../runtime/types';

/** Lazy imports, so each screen downloads only its own scripts. */
export const stitchBehaviors = {
  'intro-blueprint': () => import('./intro-blueprint'),
  'intro-minimal': () => import('./intro-minimal'),
  'not-found': () => import('./not-found'),
  'editor': () => import('./editor'),
  'editor-export': () => import('./editor-export'),
  'editor-materials-backdrop': () => import('./editor-materials-backdrop'),
  'dashboard': () => import('./dashboard'),
  'dashboard-projects': () => import('./dashboard-projects'),
  'dashboard-materials': () => import('./dashboard-materials'),
  'dashboard-specs': () => import('./dashboard-specs'),
  'dashboard-settings': () => import('./dashboard-settings'),
  'pricing': () => import('./pricing'),
  'checkout-step-1': () => import('./checkout-step-1'),
  'checkout-step-3': () => import('./checkout-step-3'),
  'auth-login': () => import('./auth-login'),
  'team': () => import('./team'),
  'notifications': () => import('./notifications'),
  'support': () => import('./support'),
  'admin': () => import('./admin'),
  'admin-accounts': () => import('./admin-accounts'),
  'admin-vault-quotas': () => import('./admin-vault-quotas'),
  'admin-security': () => import('./admin-security'),
  'admin-dieline-vault': () => import('./admin-dieline-vault'),
  'admin-print-shops': () => import('./admin-print-shops'),
  'admin-studio-monitoring': () => import('./admin-studio-monitoring'),
  'admin-revenue': () => import('./admin-revenue'),
  'admin-media': () => import('./admin-media'),
} satisfies Record<string, () => Promise<{ default: StitchBehavior }>>;

export type StitchBehaviorScreen = keyof typeof stitchBehaviors;
