// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/4381d704e493424fa6ac99d748c04765.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  try {
    document.addEventListener('click', function (e) {
      const btn = e.target.closest('[data-node]');
      if (btn) {
        const nodeKey = btn.getAttribute('data-node');
        const cta = document.getElementById('btn-main-cta');
        if (nodeKey && window.__openNodeModal) {
          window.__openNodeModal(nodeKey);
        } else if (btn.id === 'btn-main-cta' || nodeKey) {
          const event = new CustomEvent('open-node', {
            detail: nodeKey
          });
          window.dispatchEvent(event);
        }
      }
      if (e.target.closest('#btn-main-cta')) {
        const caliperBtn = document.querySelector('[data-node="caliper"]');
        if (caliperBtn) caliperBtn.click();
      }
    });
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  return {
    handlers: {
    },
  };
});
