// @ts-nocheck — machine-converted classic script; types are checked at the defineStitchBehavior boundary.
/* AUTO-GENERATED by `npm run stitch:sync` from source/5880d8d9915f4a66b008c59381278cd0.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import { defineStitchBehavior } from '../runtime/defineStitchBehavior';

export default defineStitchBehavior((scope) => {
  const { window, document, setTimeout, clearTimeout, setInterval, clearInterval, requestAnimationFrame, cancelAnimationFrame } = scope;

  // Classic scripts publish top-level functions on window.
  window.toggleMember = toggleMember;

  try {
    (function () {
      // Tab switching vanilla JS
      const tabButtons = document.querySelectorAll('.tab-btn');
      const tabContents = document.querySelectorAll('.tab-content');
      tabButtons.forEach(btn => {
        btn.addEventListener('click', () => {
          const targetTab = btn.getAttribute('data-tab');
          tabButtons.forEach(b => {
            b.classList.remove('bg-white', 'text-forest', 'shadow-sm');
            b.classList.add('text-stone-600');
          });
          btn.classList.add('bg-white', 'text-forest', 'shadow-sm');
          btn.classList.remove('text-stone-600');
          tabContents.forEach(content => {
            content.classList.remove('active');
            if (content.id === targetTab) {
              content.classList.add('active');
            }
          });
        });
      });

      // Production lock toggle safety confirmation
      const lockSwitch = document.getElementById('productionLockSwitch');
      if (lockSwitch) {
        lockSwitch.addEventListener('change', function (e) {
          if (!e.target.checked) {
            const confirmUnlock = confirm('Cảnh báo an toàn: Bạn có chắc chắn muốn mở khóa bản vẽ sản xuất? Xưởng in Đông Bắc CNC có thể đang đọc dao bế v3.4.');
            if (!confirmUnlock) {
              e.target.checked = true;
            }
          }
        });
      }
    })();
  } catch (error) {
    console.error('[stitch] script 1 failed', error);
  }

  function toggleMember(card) {
    const allCards = document.querySelectorAll('.member-card');
    const isAlreadyActive = card.classList.contains('ring-2');
    allCards.forEach(c => {
      c.classList.remove('ring-2', 'ring-forest/20', 'bg-white', 'scale-[1.015]', 'shadow-md');
      c.classList.add('bg-stone-50/60');
      const detail = c.querySelector('.member-detail');
      if (detail) detail.classList.add('hidden');
      const icon = c.querySelector('.expand-icon');
      if (icon) icon.style.transform = 'rotate(0deg)';
    });
    if (!isAlreadyActive) {
      card.classList.remove('bg-stone-50/60');
      card.classList.add('ring-2', 'ring-forest/20', 'bg-white', 'scale-[1.015]', 'shadow-md');
      const detail = card.querySelector('.member-detail');
      if (detail) detail.classList.remove('hidden');
      const icon = card.querySelector('.expand-icon');
      if (icon) icon.style.transform = 'rotate(180deg)';
    }
  }

  return {
    handlers: {
      /* click */ "0": function (event) {
        toggleMember(this);
      },
      /* click */ "1": function (event) {
        toggleMember(this);
      },
      /* click */ "2": function (event) {
        toggleMember(this);
      },
      /* click */ "3": function (event) {
        toggleMember(this);
      },
    },
  };
});
