/* AUTO-GENERATED by `npm run stitch:sync` from source/d49107077c4245a2bfb98fa622de346e.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import EditorMaterialsBackdropPage from '@/views/editor/materials/backdrop';

export const metadata: Metadata = { title: "WrapFit — Chi Tiết Vật Liệu & Bộ Sưu Tập Backdrop Động" };

export default EditorMaterialsBackdropPage;
