/* AUTO-GENERATED by `npm run stitch:sync` from source/d934fa86862742b4a873e9e9fee5126d.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import DashboardSpecsPage from '@/views/dashboard/specs';

export const metadata: Metadata = { title: "WrapFit — Quản Lý Dự Án & Chi Tiết Thông Số Kỹ Thuật" };

export default DashboardSpecsPage;
