import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));

export const FE_ROOT = path.resolve(here, '../../..');
export const STITCH_DIR = path.join(FE_ROOT, 'stitch');
export const SOURCE_DIR = path.join(STITCH_DIR, 'source');
export const MANIFEST_FILE = path.join(STITCH_DIR, 'screens.json');
export const OVERRIDES_FILE = path.join(STITCH_DIR, 'overrides.json');
export const ASSET_INDEX_FILE = path.join(STITCH_DIR, 'assets.json');

export const APP_DIR = path.join(FE_ROOT, 'src/app');
export const VIEWS_DIR = path.join(FE_ROOT, 'src/views');
export const STYLES_DIR = path.join(FE_ROOT, 'src/assets/styles/stitch');
export const SCREEN_STYLES_DIR = path.join(STYLES_DIR, 'screens');
export const FEATURE_DIR = path.join(FE_ROOT, 'src/features/stitch');
export const BEHAVIOR_DIR = path.join(FEATURE_DIR, 'behaviors');

export const PUBLIC_IMAGE_DIR = path.join(FE_ROOT, 'public/stitch/img');
export const PUBLIC_FONT_DIR = path.join(FE_ROOT, 'public/stitch/fonts');
export const PUBLIC_IMAGE_URL = '/stitch/img';
export const PUBLIC_FONT_URL = '/stitch/fonts';

/** Banner for every generated file, so nobody edits output by hand. */
export const generatedBanner = (source) =>
  `AUTO-GENERATED by \`npm run stitch:sync\` from ${source}. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead.`;

/** `/admin/revenue` → `src/app/admin/revenue/page.tsx`; `not-found` → `src/app/not-found.tsx`. */
export function pageFileFor(route) {
  if (route === 'not-found') return path.join(APP_DIR, 'not-found.tsx');
  return path.join(APP_DIR, route.replace(/^\//, ''), 'page.tsx');
}

/** `/admin/revenue` → `admin/revenue`; `/` → `home`; `not-found` → `not-found`. Path of the screen under `src/views`. */
export function viewPathFor(route) {
  return route.replace(/^\//, '') || 'home';
}

/** `/admin/revenue` → `src/views/admin/revenue/index.tsx`. */
export function viewFileFor(route) {
  return path.join(VIEWS_DIR, viewPathFor(route), 'index.tsx');
}
