/* AUTO-GENERATED by `npm run stitch:sync` from source/e54f17a8714b4cda91525b4c4720ae9e.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import EditorInspectFefcoPage from '@/views/editor/inspect/fefco';

export const metadata: Metadata = { title: "WrapFit — Giải Phẫu Bóc Tách Cấu Trúc Bao Bì CAD Chuẩn In FEFCO" };

export default EditorInspectFefcoPage;
