/* AUTO-GENERATED by `npm run stitch:sync` from source/583071fa9dec46e9884ca06cbdef850c.html. Do not edit; change the source, stitch/overrides.json or scripts/stitch instead. */
import type { Metadata } from 'next';
import EditorPage from '@/views/editor';

export const metadata: Metadata = { title: "WrapFit — Studio Thiết Kế Bản Vẽ Dieline CAD & Không Gian Gập Mở 3D Chuẩn In" };

export default EditorPage;
